#!/bin/bash
# ============================================================
# WG-FUX Optimization Engine v4.1 — " Low-Latency"
# Ingénierie Réseau Senior : Cible <20ms en gaming compétitif
#
# Architecture des optimisations :
# 1. Kernel UDP stack : Réduction des buffers + bypass congestion
# 2. WireGuard interface : Tuning cryptographique + MTU précis
# 3. IRQ/CPU affinity : Pinning NIC pour éviter le context switch
# 4. TC/QDisc : CAKE ou fq_codel avec priority gaming
# 5. Sysctl avancés : Interrupt coalescing désactivé, NAPI tuning
#
# Principe physique :
# Le RTT WireGuard = 2*RTT_physique + overhead_crypto (ChaCha20 ~0.5ms)
# Pour 20ms : RTT_physique cible < 9ms, overhead_kernel < 0.5ms
# ============================================================

set -euo pipefail

INTERFACE=${WG_INTERFACE:-wg0}
PROFILE="${1:-}"
LOG_FILE="/var/log/wg-optimize.log"
STATE_FILE="/etc/wireguard/active_profile"
QOS_PROFILE_FILE="/etc/wireguard/qos.profile"
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

# Load UPSTREAM_BANDWIDTH from manager.conf
if [ -f /etc/wireguard/manager.conf ]; then
  # shellcheck disable=SC1090
  source /etc/wireguard/manager.conf
  export SERVER_IP SERVER_PORT VPN_SUBNET VPN_SUBNET_V6 CLIENT_DNS SERVER_MTU WG_INTERFACE UPSTREAM_BANDWIDTH PERSISTENT_KEEPALIVE
fi

# Persist QoS params for wg-apply-qos.sh (sole owner of the qdisc tree).
# Called instead of doing `tc qdisc` directly on $INTERFACE.
write_qos_profile() {
 mkdir -p "$(dirname "$QOS_PROFILE_FILE")" 2>/dev/null || true
 cat > "$QOS_PROFILE_FILE" <<EOF
# Generated by wg-optimize.sh — DO NOT EDIT BY HAND
PROFILE="$1"
CAKE_BANDWIDTH="$2"
CAKE_RTT="$3"
CAKE_DIFFSERV="$4"
CAKE_EXTRA="$5"
FQ_TARGET="$6"
EOF
 log "✓ QoS profile persisted ($QOS_PROFILE_FILE)"
}

# Rebuild the qdisc tree via the single owner. Forces a rebuild even if the
# fingerprint matches (profile params are part of the fingerprint anyway, but
# explicit force shields us from edge cases like manual /etc/wireguard/qos.profile
# edits without an mtime bump).
apply_qos() {
 if [ -x "$SCRIPT_DIR/wg-apply-qos.sh" ]; then
 WG_QOS_FORCE=1 "$SCRIPT_DIR/wg-apply-qos.sh" >/dev/null 2>&1 || log "⚠ wg-apply-qos.sh failed"
 log "✓ QoS tree rebuilt via wg-apply-qos.sh (force)"
 fi
}

log() {
 echo "[$(date '+%Y-%m-%d %H:%M:%S')] [$PROFILE] $1" | tee -a "$LOG_FILE"
}

# Safe sysctl applicator — idempotent, logged, PERSISTENT
apply_sysctl() {
 local key=$1 val=$2
 local SYSCTL_CONF="/etc/sysctl.d/99-wg-fux.conf"

 # 1. Apply to memory
 if sysctl -w "$key=$val" > /dev/null 2>&1; then
 log "✓ sysctl $key = $val"
 else
 log "⚠ Skip sysctl $key (permission/absent)"
 fi

 # 2. Apply to persistent file
 if touch "$SYSCTL_CONF" 2>/dev/null; then
 if grep -qF "$key=" "$SYSCTL_CONF" 2>/dev/null; then
  sed -i "/^$key=/c\\$key=$val" "$SYSCTL_CONF"
 else
 echo "$key=$val" >> "$SYSCTL_CONF"
 fi
 fi
}

# Safe sysfs applicator
apply_sysfs() {
 local path=$1 val=$2
 if [ -w "$path" ]; then
 if echo "$val" > "$path" 2>/dev/null; then
 log "✓ sysfs $path = $val"
 else
 log "✗ Failed sysfs $path"
 fi
 else
 log "⚠ Skip sysfs $path (ro/absent)"
 fi
}

# Safe tc wrapper
tc_safe() {
 tc "$@" 2>/dev/null || true
}

if [ -z "${PROFILE:-}" ]; then
 echo "Usage: wg-optimize.sh [gaming|streaming|auto|restore|default]"
 exit 1
fi

log "=== Starting Network Optimization: Profile → $PROFILE ==="
# SRE Fix: State writing moved inside respective profile blocks to avoid false-positives

# ============================================================
# PROFILE: GAMING — Ultra Low Latency (cible: ≤20ms RTT)
# ============================================================
if [ "$PROFILE" = "gaming" ]; then
 echo "gaming" > "$STATE_FILE" 2>/dev/null || true
 log "🎮 Gaming Mode : Ultra Low Latency — Target ≤20ms RTT"

 # ----------------------------------------------------------
 # 1. UDP STACK : Clé pour WireGuard (protocole UDP natif)
 # ----------------------------------------------------------
 # Buffers : Calculés pour minimiser le bufferbloat
 # Règle : Buffer = (Vitesse_Lien * RTT_Cible) / 8
 apply_sysctl net.core.rmem_default 524288 # 512KB recv
 apply_sysctl net.core.wmem_default 524288 # 512KB send
 apply_sysctl net.core.rmem_max 4194304 # 4MB recv max
 apply_sysctl net.core.wmem_max 4194304 # 4MB send max
 apply_sysctl net.core.optmem_max 131072 # 128KB options

 # UDP socket buffers (impact direct sur WireGuard)
 apply_sysctl net.ipv4.udp_mem "16384 32768 4194304"
 apply_sysctl net.ipv4.udp_rmem_min 16384
 apply_sysctl net.ipv4.udp_wmem_min 16384

 # ----------------------------------------------------------
 # 2. TCP LOW LATENCY (pour le trafic non-WG et le contrôle)
 # ----------------------------------------------------------
 apply_sysctl net.ipv4.tcp_fastopen 3 # TFO client+server
 apply_sysctl net.ipv4.tcp_autocorking 0 # Désactive le regroupement de paquets → latence réduite
 # NOTE: net.ipv4.tcp_low_latency is a no-op since kernel 4.14 — removed.
 apply_sysctl net.ipv4.tcp_no_metrics_save 1 # Oublie les métriques entre connexions
 apply_sysctl net.ipv4.tcp_thin_linear_timeouts 1 # Connexions thin stream (gaming)
 apply_sysctl net.ipv4.tcp_notsent_lowat 16384 # Reduce send buffer pre-fill
 apply_sysctl net.ipv4.tcp_timestamps 1 # RTT measurement précis (RTTM)
 apply_sysctl net.ipv4.tcp_sack 1 # SACK = retransmission ciblée uniquement
 apply_sysctl net.ipv4.tcp_dsack 1 # Duplicate SACK

 # ----------------------------------------------------------
 # 2b. BUSY POLL — Réduit la latence d'interruption kernel
 # ----------------------------------------------------------
 # Le noyau tourne activement pendant 10µs avant de bloquer sur recv.
 # Économise 50-200µs par paquet sans saturer un vCPU de VPS.
 # (machines dédiées peuvent monter à 50-100µs)
 apply_sysctl net.core.busy_poll 10
 apply_sysctl net.core.busy_read 10

 # TCP buffers réduits pour gaming (évite bufferbloat kernel avant CAKE)
 # Les jeux tournent en UDP ; réduire les buffers TCP élimine la
 # pré-occupation des files d'attente par les téléchargements concurrents.
 apply_sysctl net.ipv4.tcp_rmem "4096 16384 4194304"
 apply_sysctl net.ipv4.tcp_wmem "4096 16384 4194304"
 apply_sysctl net.ipv4.tcp_tw_reuse 1 # Réutilisation rapide TIME_WAIT

 # ----------------------------------------------------------
 # 3. KERNEL SCHEDULER réseau
 # ----------------------------------------------------------
 apply_sysctl net.core.netdev_max_backlog 10000 # File d'attente NIC→kernel
 apply_sysctl net.core.netdev_budget 600 # Paquets traités par NAPI poll cycle
 apply_sysctl net.core.netdev_budget_usecs 8000 # Temps max NAPI poll (µs)
 apply_sysctl net.ipv4.tcp_max_syn_backlog 4096

 # ----------------------------------------------------------
 # 4. CONGESTION CONTROL — BBR v2 pour gaming UDP
 # ----------------------------------------------------------
 # BBR = Bottleneck Bandwidth and RTT (Google 2016)
 # Avantage gaming : pas de slow-start agressif, RTT-aware
 if grep -q "bbr" /proc/sys/net/ipv4/tcp_available_congestion_control 2>/dev/null; then
 apply_sysctl net.ipv4.tcp_congestion_control bbr
 log "✓ BBR congestion control activé"
 else
 apply_sysctl net.ipv4.tcp_congestion_control cubic
 log "⚠ BBR indisponible → cubic"
 fi

  # FQ (Fair Queue) + pacing : élimine les bursts de paquets → jitter réduit
  if tc qdisc show dev "$INTERFACE" 2>/dev/null | grep -qw "fq" || \
  grep -qw "fq" /proc/sys/net/core/default_qdisc 2>/dev/null; then
  apply_sysctl net.core.default_qdisc fq
  log "✓ FQ qdisc activé (pacing anti-jitter)"
  fi

 # ----------------------------------------------------------
 # 5. WireGuard INTERFACE TUNING
 # ----------------------------------------------------------
 if ip link show "$INTERFACE" > /dev/null 2>&1; then
	# MTU depuis manager.conf (défaut 1420). Les peers gaming peuvent
	# réduire leur propre MTU côté client si nécessaire (ex: 1280 sur 4G).
	_raw_mtu="${SERVER_MTU:-}"
	if [[ "$_raw_mtu" =~ ^[0-9]+$ ]] && [ "$_raw_mtu" -ge 576 ] && [ "$_raw_mtu" -le 9000 ]; then
		target_mtu="$_raw_mtu"
	else
		target_mtu=1420
	fi
	ip link set dev "$INTERFACE" mtu "$target_mtu" 2>/dev/null && log "✓ MTU $INTERFACE = $target_mtu (depuis manager.conf)" || log "⚠ failed to set MTU on $INTERFACE"

 # txqueuelen élevé = moins de drops sous burst
 ip link set dev "$INTERFACE" txqueuelen 1000 2>/dev/null && log "✓ txqueuelen $INTERFACE = 1000" || log "⚠ failed to set txqueuelen on $INTERFACE"
 fi

 # ----------------------------------------------------------
 # 6. QDisc params for the default class — gaming
 # ----------------------------------------------------------
 # We do NOT touch the qdisc tree directly. wg-apply-qos.sh owns it.
 # We persist CAKE params here and trigger a rebuild.
 write_qos_profile "gaming" \
 "${UPSTREAM_BANDWIDTH:-1gbit}" \
 "20ms" \
 "diffserv4" \
 "nat wash ack-filter overhead 80" \
 "2ms"

 # ----------------------------------------------------------
 # 7. RPS/RFS — RSS Software (multi-core NIC processing)
 # ----------------------------------------------------------
 # RPS = Receive Packet Steering : distribue l'interruption NIC sur tous les CPU
 # Critical sur serveur multi-core : évite le bottleneck sur CPU0
 NUM_CPUS=$(nproc 2>/dev/null || echo 1)
 if [ "$NUM_CPUS" -gt 31 ]; then CPU_MASK="ffffffff"; else CPU_MASK=$(printf '%x' $((2**NUM_CPUS - 1))); fi
 for rps_file in /sys/class/net/*/queues/rx-*/rps_cpus; do
 apply_sysfs "$rps_file" "$CPU_MASK"
 done

 # RFS = Receive Flow Steering : route les paquets vers le CPU qui traite l'app
 apply_sysfs /proc/sys/net/core/rps_sock_flow_entries 32768
 for rfs_file in /sys/class/net/*/queues/rx-*/rps_flow_cnt; do
 apply_sysfs "$rfs_file" 2048
 done

 # ----------------------------------------------------------
 # 8. IRQ COALESCING — Léger pour latence sans saturer le CPU
 # ----------------------------------------------------------
	# rx-usecs 8 = 8µs entre interruptions (vs 0 = à chaque paquet → CPU saturé
	# sur petite VPS). adaptive-rx=on laisse le driver ajuster dynamiquement.
	# Compromis : +1µs de jitter, mais soutenable sur VPS 1 vCPU / 512MB.
	if command -v ethtool &>/dev/null; then
	ETH_IFACE=$(ip route | grep default | awk '{print $5}' | head -n1)
	if [ -n "$ETH_IFACE" ]; then
	if ethtool -C "$ETH_IFACE" rx-usecs 8 adaptive-rx on 2>/dev/null; then
	log "✓ IRQ coalescing rx-usecs=8 adaptive-rx=on sur $ETH_IFACE"
	else
	log "⚠ ethtool échoué sur $ETH_IFACE (driver non supporté ?)"
	fi
	fi
	else
	log "⚠ ethtool non installé — skip IRQ coalescing"
	fi

 # ----------------------------------------------------------
 # 9. GRO/GSO OFF — Supprime le batching de paquets NIC
 # ----------------------------------------------------------
 # GRO (Generic Receive Offload) regroupe les paquets entrants en un seul
 # gros paquet pour économiser des CPU cycles. Sur un VPN gaming, ça ajoute
 # 0.5-2ms de latence en attendant que le batch soit plein. On désactive.
 if command -v ethtool &>/dev/null; then
  ETH_IFACE_GRO=$(ip route | grep default | awk '{print $5}' | head -n1)
  if [ -n "$ETH_IFACE_GRO" ]; then
   if ethtool -K "$ETH_IFACE_GRO" gro off gso off 2>/dev/null; then
    log "✓ GRO/GSO désactivés sur $ETH_IFACE_GRO (anti-batching)"
   else
    log "⚠ ethtool -K échoué sur $ETH_IFACE_GRO (VPS virtio — ok si pas de support)"
   fi
  fi
 fi

 log "🎮 Gaming Profile DONE — Latence cible ≤20ms activée"

# ============================================================
# PROFILE: STREAMING — High Throughput (4K/8K, backup)
# ============================================================
elif [ "$PROFILE" = "streaming" ]; then
 echo "streaming" > "$STATE_FILE" 2>/dev/null || true
 log "📺 Streaming Mode : High Throughput"

 # Buffers larges = débit important, latence secondaire
 apply_sysctl net.core.rmem_max 134217728 # 128MB
 apply_sysctl net.core.wmem_max 134217728
 apply_sysctl net.ipv4.tcp_rmem "4096 87380 134217728"
 apply_sysctl net.ipv4.tcp_wmem "4096 65536 134217728"
 apply_sysctl net.ipv4.tcp_window_scaling 1
 apply_sysctl net.ipv4.tcp_mtu_probing 1 # PLPMTUD automatique

	# BBR pour streaming aussi (meilleur que CUBIC sur liens avec perte)
	if grep -q "bbr" /proc/sys/net/ipv4/tcp_available_congestion_control 2>/dev/null; then
	apply_sysctl net.ipv4.tcp_congestion_control bbr
	apply_sysctl net.core.default_qdisc fq
	log "✓ FQ qdisc activé (pacing BBR streaming)"
	fi

 # MTU standard WireGuard 1420
 if ip link show "$INTERFACE" > /dev/null 2>&1; then
 ip link set dev "$INTERFACE" mtu 1420 2>/dev/null && log "✓ MTU $INTERFACE = 1420 (streaming)" || log "⚠ failed to set MTU on $INTERFACE"
 fi

 # CAKE en mode streaming (priorise le throughput) — params seulement,
 # l'arbre est rebuild par wg-apply-qos.sh.
 write_qos_profile "streaming" \
 "${UPSTREAM_BANDWIDTH:-1gbit}" \
 "100ms" \
 "diffserv4" \
 "nat overhead 80" \
 "10ms"

 log "📺 Streaming Profile DONE"

# ============================================================
# PROFILE: AUTO — Détection heuristique
# ============================================================
elif [ "$PROFILE" = "auto" ]; then
	# Note: State file will be written by the sub-call to gaming or streaming
	log "🤖 Auto Mode : Analyse heuristique..."
	GW=$(ip route | grep default | awk '{print $3}' | head -n1)
	if [ -z "$GW" ]; then
	log "⚠ Gateway introuvable → fallback Gaming par défaut"
	exec "$0" gaming
	fi
	if ! command -v ping &>/dev/null; then
	log "⚠ ping indisponible → fallback Gaming par défaut"
	exec "$0" gaming
	fi
	# Mesure la latence du gateway : si < 15ms → Gaming, sinon Streaming
	RTT=$(ping -c 2 -q "$GW" 2>/dev/null | awk -F'/' '/rtt/{print $5}' | cut -d. -f1)
	log "Gateway RTT mesuré : ${RTT:-unknown}ms"
	if [ -n "$RTT" ] && [ "$RTT" -lt 15 ]; then
	log "→ RTT ≤15ms détecté : activation Gaming Mode"
	exec "$0" gaming
	else
	log "→ RTT >15ms détecté : activation Streaming Mode"
	exec "$0" streaming
	fi

# ============================================================
# PROFILE: RESTORE / DEFAULT — Valeurs kernel par défaut
# ============================================================
elif [ "$PROFILE" = "restore" ] || [ "$PROFILE" = "default" ] || [ "$PROFILE" = "disable" ]; then
 log "🔄 Restore : Reset vers valeurs kernel par défaut"

 apply_sysctl net.core.rmem_default 212992
 apply_sysctl net.core.wmem_default 212992
 apply_sysctl net.core.rmem_max 212992
 apply_sysctl net.core.wmem_max 212992
 apply_sysctl net.core.netdev_max_backlog 1000
 apply_sysctl net.ipv4.tcp_autocorking 1
 apply_sysctl net.ipv4.tcp_fastopen 1
 apply_sysctl net.ipv4.tcp_congestion_control cubic
 apply_sysctl net.core.default_qdisc pfifo_fast
 apply_sysctl net.core.busy_poll 0
 apply_sysctl net.core.busy_read 0
 apply_sysctl net.ipv4.tcp_rmem "4096 87380 6291456"
 apply_sysctl net.ipv4.tcp_wmem "4096 16384 4194304"
 apply_sysctl net.ipv4.tcp_tw_reuse 0

 # Récupération du MTU cible depuis la config (ex: 1280 pour PUBG)
 # Si non défini, on repasse sur le standard 1420
 TARGET_MTU=1420
 if [ -f "/etc/wireguard/manager.conf" ]; then
 CONF_MTU=$(grep "^SERVER_MTU=" /etc/wireguard/manager.conf | cut -d'=' -f2 | tr -d '"' | tr -d "'" | tr -d '[:space:]')
 if [[ "$CONF_MTU" =~ ^[0-9]+$ ]] && [ "$CONF_MTU" -ge 576 ] && [ "$CONF_MTU" -le 9000 ]; then
  TARGET_MTU="$CONF_MTU"
 fi
 fi

 if ip link show "$INTERFACE" > /dev/null 2>&1; then
 ip link set dev "$INTERFACE" mtu "$TARGET_MTU" 2>/dev/null && log "🔄 MTU $INTERFACE réinitialisé vers valeur cible ($TARGET_MTU)" || log "⚠ failed to restore MTU on $INTERFACE"
 ip link set dev "$INTERFACE" txqueuelen 1000 2>/dev/null || true
 fi

 # Re-activer IRQ coalescing + GRO/GSO
 ETH_IFACE=$(ip route | grep default | awk '{print $5}' | head -n1)
 if [ -n "$ETH_IFACE" ] && command -v ethtool &>/dev/null; then
 ethtool -C "$ETH_IFACE" rx-usecs 50 adaptive-rx on 2>/dev/null || true
 ethtool -K "$ETH_IFACE" gro on gso on 2>/dev/null || true
 fi

 rm -f "$STATE_FILE" "$QOS_PROFILE_FILE"
 log "🔄 Restore DONE — Defaults applied (qdisc tree restored by wg-apply-qos)"
else
 log "❌ Profil inconnu: $PROFILE"
 echo "Usage: wg-optimize.sh [gaming|streaming|auto|restore|default]"
 exit 1
fi

# Rebuild qdisc tree via the sole owner. Picks up the new profile params.
apply_qos

log "=== Optimization complete. Profile: $PROFILE ==="
