import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  fr: {
    dashboard: 'Tableau de bord',
    containers: 'Conteneurs',
    sales: 'Ventes',
    network: 'Réseau',
    users_manage: 'Utilisateurs',
    servers: 'Serveurs',
    logs: 'Logs',
    topology: 'Topologie',
    dns_editor: 'Éditeur DNS',
    optimization: 'Optimisation',
    audit: 'Audit',
    settings: 'Paramètres',
    logout: 'Déconnexion',
    configs: 'Configurations',
    support: 'Support',
    active_core: 'Cœur Actif',
    uptime: 'Temps Activité',
    reboot_system: 'Redémarrer Système',
    secure_portal: 'Espace Utilisateur Sécurisé',
    no_config: 'Aucune configuration disponible',
    contact_admin: "Contactez l'administrateur.",
    // Communs (réutilisés dans toutes les sections)
    refresh: 'Actualiser',
    status_active: 'Actif',
    status_expired: 'Expiré',
    status_suspended: 'Suspendu',
    unknown: 'Inconnu',
    edit: 'Éditer',
    delete: 'Supprimer',
    // Section Utilisateurs
    user_management: 'Gestion des Opérateurs',
    system_access_control: "Contrôle d'accès système",
    search_operator: 'Rechercher un opérateur...',
    create_access: 'Créer un Accès',
    col_identity: 'Identité Opérateur',
    col_role: 'Rôle Système',
    col_status: 'Statut',
    col_action: 'Intervention',
    edit_operator: 'Éditer Opérateur',
    delete_operator: 'Supprimer Opérateur',
    no_operator_found: 'Aucun opérateur trouvé',
    role_admin_label: 'Accès Root',
    role_manager_label: 'Accès Manager',
    role_viewer_label: 'Accès Opérateur',
    role_admin_badge: 'Admin',
    role_manager_badge: 'Manager',
    role_viewer_badge: 'Opérateur',
    // Modales Créer/Éditer utilisateur
    cancel: 'Annuler',
    optional: 'Optionnel',
    username_required: "Nom d'utilisateur requis",
    username_invalid:
      "Nom d'utilisateur invalide (2-64 caractères, lettres, chiffres, _ et - uniquement)",
    password_min: 'Mot de passe : 8 caractères minimum',
    passwords_mismatch: 'Les mots de passe ne correspondent pas',
    create_error: 'Erreur lors de la création',
    update_error: 'Erreur lors de la mise à jour',
    role_viewer_desc: 'Lecture seule',
    role_manager_desc: 'Gestion Clients',
    role_admin_desc: 'Accès complet',
    create_operator_title: 'Créer un Opérateur',
    create_operator_btn: "Créer l'Opérateur",
    edit_operator_title: "Éditer l'Opérateur",
    save: 'Enregistrer',
    field_username: 'Identifiant',
    field_password: 'Mot de Passe',
    field_confirm_password: 'Confirmer le Mot de Passe',
    placeholder_username: 'ex: operateur01',
    password_leave_empty: 'Laisser vide pour inchangé',
    confirm_new_password: 'Confirmer nouveau mot de passe',
    account_active: 'Compte Actif',
    account_suspended: 'Compte Suspendu',
    reset_2fa: 'Réinitialiser 2FA (TOTP)',
    resetting: 'Réinitialisation...',
    reset_2fa_ok: 'Secret 2FA réinitialisé',
    reset_2fa_err: 'Erreur reset 2FA',
    reset_2fa_confirm:
      'Réinitialiser le 2FA pour cet opérateur ? Il pourra se reconnecter sans son code actuel.',
    expiry: 'Expiration',
    identity_locked: 'Identité Verrouillée',
    access_level: "Niveau d'Accès",
    expiry_date: "Date d'Expiration",
    remove_expiry: "Supprimer l'expiration",
    account_status: 'Statut du Compte',
    suspended_hint: "L'utilisateur ne pourra plus se connecter jusqu'à réactivation.",
    new_password: 'Nouveau Mot de Passe',
    // Section Conteneurs
    create: 'Créer',
    unlimited: 'Illimité',
    status_online: 'En ligne',
    status_offline: 'Hors ligne',
    search_placeholder: 'Rechercher...',
    deselect_all: 'Désélectionner tout',
    select: 'Sélectionner',
    deselect: 'Désélectionner',
    selected: 'sélectionné(s)',
    peers: 'peers',
    export_csv: 'Exporter CSV',
    new_peer: 'Nouveau Peer',
    new_container: 'Nouveau Conteneur',
    col_name: 'Nom',
    col_container: 'Conteneur',
    peer_active: 'Peer actif',
    peer_offline: 'Peer hors ligne',
    expiring_soon: 'Bientôt',
    quota_usage: 'Utilisation Quota',
    disable: 'Désactiver',
    enable: 'Activer',
    disable_peer: 'Désactiver le peer',
    enable_peer: 'Activer le peer',
    qr_config: 'Configuration / QR Code',
    show_qr: 'Afficher la configuration QR Code',
    delete_peer: 'Supprimer le peer',
    modify: 'Modifier',
    never: 'Jamais',
    daily_quota: 'Quota journalier',
    data_total: 'Données Totales',
    burst_dl: 'Burst DL',
    burst_ul: 'Burst UL',
    realtime: 'Temps réel',
    masked_na: 'Masquée / N/A',
    delete_container: 'Supprimer le conteneur',
    total_volume: 'Volume Total',
    no_results: 'Aucun résultat',
    empty_container: 'Conteneur Vide',
    no_peers_in_container: 'Aucun peer dans ce conteneur',
    reconcile_error: 'Erreur de réconciliation',
    peers_reapplied: 'Peers ré-appliqués dans le tunnel',
    resync_failed: 'Échec de la resynchronisation',
    rescan: 'Ré-analyser',
    no_match: 'Aucun peer ne correspond à',
    delete_peers_first: "Supprimez d'abord les peers",
    resync_peers: 'Resynchroniser les peers',
    purge: 'Purger',
    ghosts: 'fantôme(s)',
    ghosts_purged: 'entrée(s) fantôme(s) purgée(s)',
    desync_detected: 'Désynchronisation détectée',
    orphans_desc: 'client(s) en base sans fichier sur le disque (fantômes).',
    missing_desc: 'client(s) avec fichiers OK mais absent(s) du tunnel WireGuard.',
    last_activity: 'Dernière activité',
    hours_72: '72 Heures',
    network_spectrum: 'Spectre Réseau',
    blackbox_log: 'Blackbox Log',
    scanning_logs: 'Analyse des logs...',
    no_logs: 'Aucun log',
    detected_active: 'DÉTECTÉ / ACTIF',
    inactive: 'INACTIF',
    real_ip: 'IP Réelle (Endpoint)',
    real_handshake: 'Handshake Réel',
    // Communs additionnels
    loading: 'Chargement…',
    // Section Paramètres
    settings_core_title: 'Paramètres Noyau',
    tab_core: 'Noyau',
    tab_security: 'Sûreté',
    tab_billing: 'Facturation',
    tab_terminal: 'Terminal',
    apply_mission: 'Appliquer Mission',
    pending_changes: 'Modifications en attente',
    unsaved_changes: 'Modifications non sauvegardées',
    err_port_invalid: 'Port invalide (1–65535)',
    err_mtu_invalid: 'MTU invalide (576–9000)',
    err_keepalive_invalid: 'Keepalive invalide (0–3600s)',
    fix_errors_before_save: 'Corriger les erreurs avant de sauvegarder',
    config_applied_ok: 'Configuration appliquée avec succès',
    config_apply_err: "Erreur lors de l'application",
    backup_created_ok: 'Sauvegarde créée avec succès',
    backup_err: 'Erreur lors du backup',
    tt_udp_port: "Port d'écoute standard WireGuard",
    tt_keepalive:
      'Maintient les sessions actives à travers les pare-feu NAT rigides via stimulation UDP (0 = désactivé).',
    keepalive_reco: 'Recommandé : 25s (Standard), 5s (Gaming Mobile Ultra-Stable).',
    tt_wg_endpoint:
      'Domaine ou IP publique inscrit dans le fichier .conf des clients VPN. Doit pointer vers ce serveur (port UDP ci-dessus).',
    ph_wg_endpoint: 'ex: vpn.mondomaine.com ou 1.2.3.4',
    endpoint_warn_1: 'Seuls les',
    endpoint_warn_new: 'nouveaux',
    endpoint_warn_2: "clients générés après la modification utiliseront ce point d'entrée.",
    tt_dns: 'Serveurs DNS transmis aux clients',
    tt_subnet: "Plage d'IP interne du tunnel vpn",
    sec_encryption_desc:
      'Protocole ChaCha20-Poly1305 actif. Rotation automatique des clés de session Curve25519.',
    sec_analyze_integrity: 'Analyser Intégrité',
    sec_packet_desc:
      'Pare-feu UFW activé. Rejet immédiat des paquets ICMP non autorisés et scans SYN furtifs.',
    sec_firewall_logs: 'Logs Firewall',
    sec_telegram_desc:
      "Vérifiez la connectivité avec votre bot Telegram. Le système envoie des alertes critiques lors des tentatives de brèche ou de déconnexion d'interface.",
    telegram_test_ok: 'Notification de test envoyée avec succès',
    telegram_test_err: 'Échec de la connexion Telegram',
    test_connection: 'Tester la Connexion',
    maint_archives_desc:
      "Exportation complète du cluster : certificats, configurations d'interfaces et database SQL cryptée.",
    maint_generate_backup: 'Générer Backup .tar.gz',
    maint_reset_desc:
      "Réinitialisation complète de l'architecture. Perte irrémédiable de toutes les routes vpn.",
    maint_factory_reset: 'Restaurer Valeurs Usine',
    // Facturation
    configured_badge: 'configuré',
    secret_keep_placeholder: '•••••••• (laisser vide pour conserver)',
    settings_load_err: 'Erreur de chargement des réglages',
    settings_saved: 'Réglages enregistrés',
    settings_save_err: "Erreur d'enregistrement",
    billing_stripe_title: 'Stripe — Renouvellement auto',
    billing_stripe_desc_1:
      "Les revendeurs top-level achètent leurs crédits par Stripe Checkout (1 crédit = 30 jours de licence pour 1 serveur — le renouvellement débite le portefeuille automatiquement). Configurez l'URL du webhook Stripe sur",
    billing_stripe_desc_2: 'Sans Stripe, le contact ci-dessous est affiché aux revendeurs.',
    f_stripe_secret: 'Clé secrète Stripe',
    f_stripe_webhook: 'Secret du webhook',
    f_stripe_publishable: 'Clé publiable',
    f_stripe_price_id: 'ID de prix (Price ID)',
    f_credit_price: "Prix d'1 crédit (centimes)",
    ph_credit_price: 'ex: 1500 = 15,00 €',
    f_currency: 'Devise (ISO)',
    billing_platform: 'Plateforme',
    f_terms_url: "URL des CGU (exigées à l'inscription si définie)",
    f_update_paused: 'Pause des mises à jour flotte (1 = gelées)',
    billing_payment_contact: 'Contact de paiement',
    billing_payment_contact_desc:
      "Affiché aux revendeurs pour renouveler quand Stripe n'est pas actif (paiement manuel via WhatsApp/Telegram).",
    f_telegram_contact: 'Telegram (contact)',
    f_payment_instructions: 'Instructions de paiement',
    ph_payment_instructions: 'ex: Virement / PayPal — 15€/mois par VPS',
    billing_telegram_bot: 'Bot Telegram (alertes)',
    f_bot_token: 'Token du bot',
    // Optimisation
    optim_reactivated: 'Optimisation réactivée',
    optim_disabled: 'Optimisations système désactivées (Tunnel préservé)',
    optim_toggle_err: 'Échec du basculement SRE',
    optim_profile_prefix: 'Profil',
    optim_profile_activated: 'activé avec succès',
    optim_sync_err: 'Échec de la synchronisation neurale',
    optim_streaming_desc: 'Throughput maximal. Optimisation BBR & MTU 1280.',
    optim_auto_desc: 'Analyse heuristique & ajustement dynamique du MTU.',
    optim_sync_desc:
      'Maintenance heuristique du noyau système active. Surveillance en temps réel des fuites mémoires.',
    optim_system_optimized: 'Système Optimisé',
    optim_active_vector: 'Vecteur Actif',
    optim_active: 'Optimisation Active',
    optim_activate_profile: 'Activer Profil',
    // Dashboard
    quota_critical_suffix: 'en Quota Critique',
    manage: 'Gérer',
    dash_active_protocol: 'Protocole Actif',
    dash_active_peers: 'Peers Actifs',
    dash_connected: 'CONNECTÉS',
    dash_port_link: 'Port Liaison',
    subscribers: 'Abonnés',
    expire_soon_days: 'Expirent ≤ 7 j',
    expired_count: 'Expirés',
    most_active_client: 'Client le plus actif',
    none: 'Aucun',
    inactive_station: 'Station Inactive',
    telemetry_system: 'Système SENTINEL',
    telemetry_live: 'Télémétrie Live',
    history_unavailable: 'Historique indisponible — données temps réel actives',
    init_sentinel_flux: 'Initialisation des flux Sentinel...',
    check_traffic_history_conn: 'Vérifier la connexion au service traffic-history',
    data_after_audit: "(Données disponibles après le premier cycle d'audit)",
    rt_rates_label: 'Débits temps réel (5 s) · Mbit/s',
    history_24h_label: 'Historique 24 h · volumes MB',
    tactical_distribution: 'Répartition Tactique',
    no_flux_detected: 'Aucun flux détecté',
    test_running: 'Test en cours...',
    rerun: 'Relancer',
    run_speedtest: 'Lancer Test de Flux',
    // Audit
    audit_title: 'Audit de Sécurité',
    integrity_index: "Indice d'Intégrité",
    integrity_desc: "Calcul basé sur l'état du noyau, du firewall et des protections logicielles.",
    critical: 'Critique',
    audit_firewall_desc:
      "Vérification de l'interface UFW et des règles de filtrage pré-configurées.",
    audit_fw_ok: 'Protection Périphérique OK',
    audit_fw_bad: 'Vulnérabilité Réseau Possible',
    audit_ipfwd_desc: "État de l'option sysctl net.ipv4.ip_forward nécessaire au transit vpn.",
    audit_ipfwd_ok: 'Transit de Données Actif',
    audit_ipfwd_bad: 'Interruption Flux Tunnel',
    audit_f2b_desc: 'Surveillance des tentatives de brute-force SSH et des bannissements IP.',
    audit_f2b_ok: 'Defense Brute-Force OK',
    audit_f2b_bad: 'Vulnérabilité SSH Détectée',
    audit_disk_desc: 'Utilisation de la partition racine (SSD/NVMe) pour le cache système.',
    // Logs
    system_event: 'Événement système',
    system_source: 'Système',
    logs_cleared_ok: 'Journaux effacés avec succès',
    logs_clear_err: "Erreur lors de l'effacement",
    ws_lost: 'Connexion temps réel perdue — Reconnexion automatique en cours...',
    docker_logs_prefix: 'Logs des conteneurs Docker',
    clear_all_logs_q: 'Effacer tous les journaux ?',
    action_irreversible: 'Cette action est irréversible.',
    confirm_clear: "Confirmer l'effacement",
    filter_placeholder: 'Filtrer...',
    filter_logs_aria: 'Filtrer les logs',
    tab_access_peers: 'Accès Peers',
    log_tab_security: 'Sécurité',
    tab_system_log: 'Journal Système',
    entries: 'entrées',
    clear: 'Effacer',
    col_event: 'Événement',
    scanning_archives: 'Scanning archives...',
    no_record_found: 'Aucun enregistrement détecté',
    // MainLayout
    twofa_banner_text: "Votre compte admin n'a pas de 2FA activé —",
    twofa_banner_cta: 'configurer maintenant',
    upd_phase_queued: 'En file d’attente…',
    upd_phase_downloading: 'Téléchargement du bundle…',
    upd_phase_verifying: 'Vérification d’intégrité…',
    upd_phase_building: 'Reconstruction des services…',
    upd_phase_restarting: 'Redémarrage…',
    upd_restarting_services: 'Redémarrage des services…',
    upd_installing: 'Installation en cours…',
    license_expired_msg:
      'Licence expirée — la création de clients est bloquée. Renouvelez pour continuer.',
    license_label: 'Licence :',
    days_remaining: 'jour(s) restant(s)',
    license_renew_hint: 'pensez à renouveler.',
    renew_via: 'Pour renouveler :',
    upd_failed_prefix: 'Échec de la mise à jour',
    upd_retry_next_cycle: 'Nouvelle tentative automatique au prochain cycle.',
    upd_label: 'Mise à jour',
    upd_installed_reload: 'installée — rechargement du panneau…',
    upd_dont_close:
      'Ne fermez pas cette page — coupure réseau brève (~30 s) pendant le redémarrage.',
    upd_ready_confirm: "prête — votre confirmation est requise pour l'installer.",
    upd_scheduled: 'programmée',
    upd_around: 'vers',
    upd_can_advance: "vous pouvez l'avancer.",
    upd_install_now: 'Installer maintenant',
    upd_available: 'Mise à jour disponible',
    upd_pending_approval: 'en attente d’approbation par la plateforme.',
    onboarding_add_vps: 'Ajoutez votre VPS pour accéder au reste de la plateforme',
    access_denied_admin: 'Accès refusé — section réservée aux administrateurs',
    search: 'Rechercher',
    surveillance_active: 'Surveillance Active',
    sentinel_offline: 'Sentinel Hors-ligne',
    dns_filtering_active: 'Filtrage DNS Actif',
    dns_interrupted: 'DNS Interrompu',
    all_rights_reserved: 'Tous droits réservés.',
    delete_client: 'Supprimer le client',
    delete_permanently: 'Supprimer définitivement',
    delete_empty_container: 'Supprimer le conteneur vide',
    revoke_access_warning: 'Cette action révoquera immédiatement ses accès système.',
    from_container: 'du conteneur',
    // StatusWidget / NavItems
    wg_restarted_ok: 'Service WireGuard redémarré.',
    wg_restart_error: 'Erreur lors du redémarrage.',
    restarting_label: 'Redémarrage...',
    confirm: 'Confirmer',
    change_language: 'Changer de langue',
    restart_wireguard: 'Redémarrer WireGuard',
    restart_wireguard_q: 'Redémarrer WireGuard ?',
    yes: 'Oui',
    no: 'Non',
    // Auth
    login_invalid_credentials: 'Identifiants invalides',
    login_too_many: 'Trop de tentatives. Réessayez plus tard.',
    login_error: 'Erreur de connexion',
    login_step_access: 'Accès',
    login_headline_1: 'Tunnel.',
    login_headline_2a: 'À',
    login_headline_2b: 'toi.',
    login_tagline:
      "Une interface de contrôle pour ton réseau WireGuard. Provisionne, supervise, ferme la porte d'un geste — sans quitter ton terminal mental.",
    meta_status: 'Statut',
    meta_operational: 'Opérationnel',
    meta_latency: 'Latence',
    meta_time: 'Heure',
    sovereign_edition: 'Édition souveraine',
    login_step_verification: 'Vérification',
    login_step_identification: 'Identification',
    hide_label: 'Masquer',
    show_label: 'Afficher',
    remember_session: 'Mémoriser la session',
    totp_label: 'Code authenticator',
    totp_hint: '6 chiffres — application authenticator',
    login_connecting: 'Connexion en cours…',
    login_validate_code: 'Valider le code',
    login_enter_tunnel: 'Entrer dans le tunnel',
    forgot_credentials: 'Identifiants oubliés ?',
    contact_admin_short: 'contact admin',
    register_failed: "Échec de l'inscription",
    register_subtitle: 'Inscription revendeur',
    verifying: 'Vérification…',
    invite_invalid: 'Invitation invalide ou expirée.',
    account_created: 'Compte créé ! Vous pouvez vous connecter.',
    sign_in: 'Se connecter',
    invited_by: 'Invité par',
    ph_username_simple: "Nom d'utilisateur",
    ph_password_min8: 'Mot de passe (min 8 caractères)',
    ph_email_reco: 'Email (recommandé — reçus & alertes)',
    accept_terms_prefix: "J'accepte les",
    terms_link_label: "conditions générales d'utilisation",
    creating: 'Création…',
    create_my_account: 'Créer mon compte',
    // Serveurs
    srv_status_pending: 'En attente',
    srv_status_provisioning: 'Provisioning',
    srv_status_error: 'Erreur',
    just_now: "à l'instant",
    ago_prefix: 'il y a',
    ago_suffix: '',
    unit_min: 'min',
    unit_hour: 'h',
    unit_day: 'j',
    update_available_cron: 'Mise à jour disponible (appliquée par le cron quotidien)',
    up_to_date: 'À jour',
    deploy_version_title: 'Déployer la version',
    deploy_approved_hint:
      'Seules les instances approuvées ici recevront la mise à jour (≤ 30 min).',
    select_all: 'Tout sélectionner',
    instances_word: 'instance(s)',
    no_instance_enrolled: 'Aucune instance enrôlée',
    deploy_mode: 'Mode de déploiement',
    deploy_scheduled_title: 'Programmé (défaut)',
    deploy_scheduled_desc: 'Appliquée automatiquement sous ~6 h, sans intervention.',
    deploy_instant_title: 'Instantané',
    deploy_instant_desc:
      'L’instance la reçoit tout de suite — son opérateur confirme l’installation.',
    cancel_deployment: 'Annuler le déploiement',
    cancel_deployment_title:
      "Retire l'approbation : ces instances ne recevront plus la mise à jour",
    close: 'Fermer',
    push_update: 'Pousser la mise à jour',
    scheduled_badge: 'programmée',
    deploy_already_scheduled: 'Déploiement déjà programmé',
    install_command: 'Commande d’installation',
    oneliner_validity: 'valable 10 minutes, usage unique',
    oneliner_desc:
      'À coller en root sur le VPS. Réinstalle ou installe l’instance ; la licence du serveur est conservée.',
    copied: 'Copié',
    copy: 'Copier',
    lic_expired: 'Expirée',
    expires_today: "Expire aujourd'hui",
    days_left: 'j restants',
    renew_1_month: '+ 1 mois',
    renew_3_months: '+ 3 mois',
    renew_1_year: '+ 1 an',
    channel_stable: 'Stable',
    channel_canary: 'Canary (pilote)',
    channel_hold: 'Gelé (aucune maj)',
    license: 'Licence',
    current_status: 'Statut actuel :',
    ph_custom_days: 'Délai personnalisé (jours)',
    apply: 'Appliquer',
    client_cap_label: 'Plafond de clients (vide = illimité)',
    ph_unlimited: 'illimité',
    update_channel_label: 'Canal de mise à jour',
    cut_unpaid: 'Couper (impayé)',
    uninstall_wgfux: 'Désinstaller wg-fux',
    uninstall_warning:
      'Arrête et supprime les conteneurs, volumes (clients WireGuard inclus) et la configuration sur le VPS lui-même. Irréversible.',
    type_to_confirm_prefix: 'Tapez',
    type_to_confirm_suffix: 'pour confirmer',
    uninstalling: 'Désinstallation…',
    uninstall_permanently: 'Désinstaller définitivement',
    srv_load_err: 'Erreur de chargement des serveurs',
    server_deleted: 'Serveur supprimé',
    delete_error: 'Erreur lors de la suppression',
    wgfux_uninstalled: 'wg-fux désinstallé du VPS',
    uninstall_error: 'Erreur lors de la désinstallation',
    deploy_cancelled_for: 'Déploiement annulé pour',
    approved_for: 'approuvée pour',
    deploy_error: 'Erreur de déploiement',
    server_updated: 'Serveur mis à jour',
    srv_online_suffix: 'en ligne',
    srv_unreachable_suffix: 'injoignable',
    probe_failed: 'Sonde échouée',
    servers_deleted_suffix: 'serveur(s) supprimé(s)',
    licenses_extended_suffix: 'licence(s) prolongée(s)',
    bulk_action_failed: 'Action groupée échouée',
    oneliner_gen_error: 'Erreur de génération du one-liner',
    license_cut: 'Licence coupée',
    update_channel_prefix: 'Canal de mise à jour :',
    client_cap_removed: 'Plafond de clients retiré',
    cap_prefix: 'Plafond :',
    clients_word: 'client(s)',
    license_extended_until: "Licence prolongée jusqu'au",
    renew_error: 'Erreur lors du renouvellement',
    srv_filter_ph: 'Filtrer (nom, hôte, statut…)',
    deploy_btn: 'Déployer',
    add_vps: 'Ajouter un VPS',
    licenses_7d: 'Licences ≤ 7 j',
    clients_fleet: 'Clients (flotte)',
    pending_updates: 'Maj en attente',
    extend_licenses: 'Prolonger licences',
    days_to_add: 'Jours à ajouter',
    col_server: 'Serveur',
    col_address: 'Adresse',
    col_load: 'Charge',
    col_version: 'Version',
    col_license: 'Licence',
    col_last_contact: 'Dernier contact',
    view_detail: 'Voir le détail',
    unnamed: 'Sans nom',
    channel_word: 'canal',
    probe_now: 'Sonder maintenant (SSH)',
    edit_meta_alerts: 'Éditer (métadonnées, alertes)',
    install_command_oneliner: 'Commande d’installation (one-liner)',
    manage_license: 'Gérer la licence',
    uninstall_from_vps: 'Désinstaller wg-fux du VPS',
    delete_server: 'Supprimer le serveur',
    no_server_matches_filter: 'Aucun serveur ne correspond au filtre',
    no_server_registered: 'Aucun serveur enregistré',
    add_first_vps: '+ Ajouter votre premier VPS',
    edit_server: 'Éditer le serveur',
    f_label: 'Label',
    f_host: 'Host',
    f_ssh_port: 'Port SSH',
    f_region: 'Région',
    f_provider: 'Fournisseur',
    f_tags_csv: 'Tags (séparés par des virgules)',
    f_notes: 'Notes',
    alerts_empty_disabled: 'Alertes (vide = désactivé)',
    f_offline_minutes: 'Offline > N minutes',
    f_license_days: 'Licence < N jours',
    no_history_yet: 'Aucun historique encore collecté.',
    availability: 'Disponibilité',
    points: 'points',
    probe: 'Sonder',
    last_error: 'Dernière erreur',
    disk: 'Disque',
    telemetry_from: 'télémétrie du',
    clients_label: 'Clients',
    target_server: 'Serveur cible',
    this_server: 'Ce serveur',
    no_server_online: 'Aucun serveur en ligne. Enregistrez un VPS dans l’onglet Serveurs.',
    // Réseau
    reason_topup: 'Rechargement',
    reason_topup_stripe: 'Achat Stripe',
    reason_transfer_in: 'Reçu',
    reason_transfer_out: 'Envoyé',
    reason_monthly: 'Débit mensuel',
    reason_client_renewal: 'Renouvellement client',
    reason_license_renewal: 'Renouvellement licence',
    reason_refund: 'Remboursement',
    net_load_err: 'Erreur de chargement du réseau',
    subreseller_created: 'Sous-revendeur créé',
    err_creation: 'Erreur création',
    credits_transferred: 'Crédits transférés',
    err_transfer: 'Erreur transfert',
    account_credited: 'Compte crédité',
    err_topup: 'Erreur top-up',
    err_payment: 'Erreur de paiement',
    sell_price_saved: 'Prix de revente enregistré',
    err_price: 'Erreur prix',
    brand_saved: 'Marque enregistrée',
    err_brand: 'Erreur marque',
    payment_contact_saved: 'Contact de paiement enregistré',
    err_contact: 'Erreur contact',
    err_reset: 'Erreur reset',
    email_of: 'Email de',
    email_updated: 'Email mis à jour',
    net_subtitle: 'Crédits · Revendeurs · Marge',
    balance: 'Solde',
    low: 'Bas',
    credits_word: 'crédits',
    margin: 'Marge',
    resale_minus_acquisition: 'revente − acquisition',
    subresellers: 'Sous-revendeurs',
    linked_accounts: 'comptes rattachés',
    buy_credits: 'Acheter des crédits',
    buy_credits_desc:
      '1 crédit = 30 jours de licence pour 1 serveur. Le renouvellement débite le portefeuille automatiquement. Les sous-revendeurs achètent auprès de leur revendeur parent.',
    ph_credits_count: 'nombre de crédits',
    pay_by_card: 'Payer par carte',
    my_sell_price: 'Mon prix de revente',
    my_sell_price_desc:
      'Prix facturé à votre réseau pour 1 crédit (en centimes). Votre marge = revente − acquisition.',
    ph_cents_per_credit: 'centimes / crédit',
    topup_account: 'Créditer un compte (top-up)',
    ph_credits: 'crédits',
    ph_price_per_credit: 'prix/crédit (centimes)',
    credit_btn: 'Créditer',
    my_network: 'Mon réseau',
    ph_search_network: 'Rechercher (nom, email, #id)…',
    col_account: 'Compte',
    col_balance: 'Solde',
    col_clients: 'Clients',
    col_license_soon: 'Licence proche',
    col_sell_price: 'Prix revente',
    col_actions: 'Actions',
    subreseller_word: 'sous-revendeur',
    reseller_word: 'revendeur',
    disabled_status: 'Désactivé',
    online_suffix: 'en ligne',
    expired_short: 'Expirée',
    ph_cents: 'centimes',
    price_updated: 'Prix mis à jour',
    edit_sell_price: 'Modifier le prix de revente',
    transfer_btn: 'Transférer',
    prefill_transfer: 'Pré-remplir le transfert de crédits',
    prefill_topup: 'Pré-remplir le top-up',
    edit_email: "Modifier l'email",
    reset_password: 'Réinitialiser le mot de passe',
    account_disabled_msg: 'Compte désactivé',
    account_reenabled_msg: 'Compte réactivé',
    cut_account_access: 'Couper l’accès de ce compte',
    restore_access: 'Rétablir l’accès',
    no_account_matches: 'Aucun compte ne correspond',
    no_subreseller: 'Aucun sous-revendeur',
    page_word: 'Page',
    accounts_word: 'comptes',
    prev_short: 'Préc.',
    next_short: 'Suiv.',
    new_subreseller: 'Nouveau sous-revendeur',
    ph_password_min: 'mot de passe (min 8)',
    ph_sell_price_opt: 'prix revente/crédit (centimes, opt.)',
    transfer_credits: 'Transférer des crédits',
    ph_recipient_userid: 'userId destinataire',
    payment_contact: 'Contact de paiement',
    payment_contact_desc:
      'Affiché aux clients d’une instance quand la licence expire (vente manuelle sans Stripe).',
    ph_whatsapp: 'WhatsApp (+33…)',
    ph_telegram: 'Telegram (@handle)',
    ph_payment_instructions_short: 'Instructions de paiement…',
    brand_white_label: 'Marque (white-label)',
    ph_brand_name: 'Nom de marque',
    ph_logo_url: 'URL du logo (https://…)',
    ph_brand_color: 'Couleur (#RRGGBB)',
    ph_custom_domain: 'Domaine perso (vpn.exemple.com)',
    credits_ledger: 'Relevé de crédits',
    all_movements: 'Tous les mouvements',
    ph_ref: 'Réf…',
    col_movement: 'Mouvement',
    col_credits: 'Crédits',
    col_price: 'Prix',
    col_ref: 'Réf.',
    no_movement: 'Aucun mouvement',
    password_reset_title: 'Mot de passe réinitialisé',
    password_reset_hint_1: 'Transmettez-le à',
    password_reset_hint_2: 'Il ne sera plus affiché.',
    invite_active: 'Active',
    invite_used: 'Utilisée',
    invitations: 'Invitations',
    generate_link: 'Générer un lien',
    link_generated_copied: 'Lien généré et copié (valide 7 jours)',
    err_invite: 'Erreur invitation',
    invite_revoked: 'Invitation révoquée',
    err_revoke: 'Erreur de révocation',
    col_created: 'Créée',
    col_expires: 'Expire',
    col_used_by: 'Utilisée par',
    revoke: 'Révoquer',
    no_invitation: 'Aucune invitation',
    activity_12m: 'Activité (12 mois)',
    cumulative_margin: 'Marge cumulée',
    credits_resold: 'Crédits revendus',
    acquired: 'Acquis',
    resold: 'Revendus',
    consumed: 'Consommés',
    // Ventes
    reason_transfer_in_credits: 'Crédits reçus',
    reason_transfer_out_credits: 'Crédits envoyés',
    expired_prefix: 'Expiré',
    renew_30d: '+30 j',
    renew_90d: '+90 j',
    extended_until: 'prolongé jusqu’au',
    credits_short: 'crédit(s)',
    renewal_error: 'Erreur de renouvellement',
    sales_subtitle: 'Abonnements · Renouvellements · Crédits',
    ph_filter_client: 'Filtrer un client…',
    credits_balance: 'Solde crédits',
    subscriptions: 'Abonnements',
    subscription: 'Abonnement',
    due_on: 'Échéance le',
    no_expiration: 'Sans expiration',
    unlimited_cap: 'Plafond illimité',
    credits_title: 'Crédits',
    remaining: 'restants',
    used_word: 'utilisés',
    included: 'inclus',
    pricing_note_1: 'Tarif :',
    pricing_note_2: '30 jours = 1 crédit',
    pricing_note_3:
      '. Encaissez votre client comme vous voulez, puis renouvelez ici — les crédits s’achètent auprès de votre fournisseur.',
    col_client: 'Client',
    col_subscription: 'Abonnement',
    col_state: 'État',
    col_renew: 'Renouveler',
    cut_off: 'Coupé',
    free_admin: 'Gratuit (admin)',
    credits_unit_short: 'cr',
    no_subscription_hint: 'Aucun abonnement — créez des clients dans Conteneurs',
    // DNS
    dns_upstream_title: 'Serveurs DNS Amont',
    dns_upstream_desc:
      'Entrez un serveur par ligne. Ces serveurs seront utilisés par AdGuard pour résoudre les requêtes de vos clients. Privilégiez les serveurs DoH ou DoT pour une sécurité maximale.',
    dns_bootstrap_desc:
      "Ces serveurs sont utilisés pour résoudre les noms d'hôtes des DNS amont (ex: dns.cloudflare.com).",
    dns_filtering_label: 'Filtrage AdGuard',
    dns_filtering_desc: 'Active le blocage des publicités et du tracking.',
    dns_safebrowsing_label: 'Navigation Sécurisée',
    dns_safebrowsing_desc: 'Bloque les sites malveillants et de phishing.',
    dns_parental_label: 'Contrôle Parental',
    dns_parental_desc: 'Bloque le contenu réservé aux adultes.',
    dns_safesearch_desc: 'Force le mode sécurisé sur Google, YouTube, etc.',
    blocklists: 'blocklists',
    rules: 'règles',
    ph_filter_blocklists: 'Filtrer les blocklists…',
    delete_blocklist: 'Supprimer cette blocklist',
    no_blocklist_matches: 'Aucune blocklist ne correspond',
    no_blocklist_configured: 'Aucune blocklist configurée',
    quick_add: 'Ajout rapide',
    add_custom_blocklist: 'Ajouter une blocklist personnalisée',
    ph_blocklist_name: 'Nom (ex: Steven Black)',
    ph_blocklist_url: 'URL (https://…)',
    add: 'Ajouter',
    invalid_url: 'URL invalide (attendu : https://…)',
    blocklist_already_added: 'Cette blocklist est déjà ajoutée.',
    adguard_load_err: 'Impossible de charger les données AdGuard Home',
    config_partially_applied: 'Configuration partiellement appliquée',
    dns_config_updated: 'Configuration DNS mise à jour avec succès',
    dns_save_err: 'Erreur lors de la sauvegarde de la configuration',
    blocklist_added: 'Blocklist ajoutée',
    add_error: "Erreur lors de l'ajout",
    blocklist_removed: 'Blocklist supprimée',
    dns_init: 'Initialisation DNS...',
    dns_center: 'Centre DNS',
    adguard_engine_active: 'Moteur AdGuard actif',
    no_change: 'Aucune modification',
    deploying: 'Déploiement...',
    apply_changes: 'Appliquer les modifications',
    saved: 'Enregistré',
    dns_queries: 'Requêtes',
    dns_blocked: 'Bloqués',
    last_24h: 'Dernières 24h',
    dns_latency: 'Latence',
    average: 'Moyenne',
    // Rapport utilisateur
    period_day: 'Jour',
    period_week: 'Semaine',
    period_month: 'Mois',
    chart_creations_24h: 'Créations — 24 dernières heures',
    chart_creations_7d: 'Créations — 7 derniers jours',
    chart_creations_30d: 'Créations — 30 derniers jours',
    activity_24h: '24h',
    activity_7d: '7 jours',
    activity_30d: '30 jours',
    added_24h: 'Ajoutés 24h',
    added_7d: 'Ajoutés 7j',
    added_30d: 'Ajoutés 30j',
    added_generic: 'Ajoutés',
    report_title: 'Rapport',
    expires_word: 'expire',
    clients_total: 'Clients total',
    actives: 'Actifs',
    recent_activity: 'Activité récente',
    no_peer_dot: 'Aucun peer.',
    no_activity_recorded: 'Aucune activité enregistrée',
    report_load_err: 'Impossible de charger le rapport',
    server_online: 'Serveur en ligne',
    err_label_required: 'Label requis',
    err_host_required: 'Host / IP requis',
    err_port_range: 'Port invalide (1-65535)',
    register_error: "Erreur lors de l'enregistrement",
    copy_failed: 'Copie impossible',
    ph_vps_label: 'ex: vps-paris-01',
    f_host_ip: 'Host / IP',
    ph_host_ip: 'ex: 203.0.113.10',
    register_vps: 'Enregistrer le VPS',
    provisioning_command: 'Commande de provisioning',
    paste_command_hint: 'Collez cette commande en root sur votre VPS, puis attendez ~30s.',
    provisioning_failed: 'Échec du provisioning',
    command_expired: 'Commande expirée — régénérez-la',
    waiting_for_server: 'En attente du serveur…',
    later: 'Plus tard',
    regenerate_command: 'Régénérer la commande',
    done: 'Terminé',
    copy_command: 'Copier la commande',
    vps_provisioning: 'Provisioning du VPS',
    // Modales client / conteneur
    client_name_invalid: 'Nom invalide (1-64 caractères, lettres, chiffres, _ et - uniquement)',
    invalid_duration: 'Veuillez entrer une durée de validité valide',
    peer_created_ok: 'créé avec succès',
    name_already_used_1: "Le nom '",
    name_already_used_2: "' est déjà utilisé",
    client_create_err: 'Erreur lors de la création du client',
    peer_init_title: 'Initialisation de Peer',
    f_client_name: 'Nom du Client',
    ph_client_name: 'ex: galaxy-s24',
    f_tactical_group: 'Groupe Tactique (Conteneur)',
    select_container_opt: '— Sélectionner un conteneur —',
    container_target_hint_current: 'Le client sera ajouté dans ce conteneur en cours.',
    container_target_hint_choose: 'Choisissez le conteneur de destination.',
    f_time_validity: 'Validité temporelle',
    unit_days: 'Jours',
    unit_hours: 'Heures',
    f_data_quota: 'Quota de Données',
    f_bandwidth: 'Bande passante',
    cancel_mission: 'Annuler Mission',
    init_peer_access: "Initialiser l'accès Peer",
    peer_updated_ok: 'mis à jour avec succès',
    edit_peer_title: 'Éditer Peer',
    aria_quota_gb: 'Quota en GB',
    aria_quota_slider: 'Quota de données (curseur)',
    unlimited_paren: '0 (illimité)',
    f_max_bandwidth: 'Bande Passante Max',
    aria_upload_limit: 'Limite upload en Mbps',
    aria_bandwidth_slider: 'Bande passante max (curseur)',
    aria_unlimited_on: 'Durée illimitée activée',
    aria_unlimited_off: 'Durée illimitée désactivée',
    save_btn: 'Sauvegarder',
    confirm_delete_title: 'Confirmer la suppression',
    permanent_action_warning: 'Cette action est permanente et ne peut pas être annulée.',
    new_container_title: 'Nouveau Conteneur',
    f_container_name: 'Nom du Conteneur (Groupe)',
    ph_container_name: 'ex: famille, serveurs',
    container_name_hint: 'Uniquement lettres, chiffres, tirets et underscores.',
    download_conf: 'Télécharger .conf',
    // Divers : recherche globale, monitoring SRE, noeud reseau, error boundaries
    gs_navigation: 'Navigation',
    gs_peers_section: 'Peers',
    gs_search_placeholder: 'Rechercher peers, sections, IP...',
    gs_hint: 'Peers · Sections · Adresses IP',
    gs_dashboard_desc: 'Statistiques temps réel',
    gs_containers_desc: 'Gestion des peers WireGuard',
    gs_users_desc: 'Accès opérateurs',
    gs_logs_label: 'Logs Système',
    gs_audit_desc: 'Contrôle de sécurité',
    gs_optimization_desc: 'Profils réseau',
    gs_settings_desc: 'Configuration système',
    perf_fetch_error: 'Échec de récupération de la télémétrie',
    perf_conn_error: 'Erreur de connexion',
    perf_optimal: 'Optimal',
    perf_nominal: 'Nominal',
    perf_congested: 'Congestionné',
    perf_jitter: 'Gigue',
    perf_load: 'Charge',
    perf_bloat: 'Bloat',
    nn_tact_ip: 'IP Tactique',
    nn_endpoint: 'Endpoint',
    nn_total_usage: 'Usage total',
    nn_last_seen: 'Vu pour la dernière fois',
    if_fetch_error: 'Échec de récupération des interfaces',
    version: 'Version',
    eb_component: 'Composant',
    eb_unexpected: 'Une erreur inattendue est survenue.',
    geb_title: 'Interface Corrompue',
    geb_unknown: 'Erreur inconnue',
    geb_desc:
      "Une erreur inattendue a provoqué le crash de l'interface. Les services VPN ne sont PAS affectés.",
    geb_reset: "Réinitialiser l'Interface",
    eb_critical_error: 'Erreur Critique',
    stack_trace: 'Stack Trace',
    reset: 'Réinitialiser',
    gs_logs_desc: "Journaux d'accès et sécurité",
    tactical_groups: 'Groupes Tactiques',
  },
  en: {
    dashboard: 'Dashboard',
    containers: 'Containers',
    sales: 'Sales',
    network: 'Network',
    users_manage: 'Users',
    servers: 'Servers',
    logs: 'Logs',
    topology: 'Topology',
    dns_editor: 'DNS Editor',
    optimization: 'Optimization',
    audit: 'Audit',
    settings: 'Settings',
    logout: 'Logout',
    configs: 'Configurations',
    support: 'Support',
    active_core: 'Active Core',
    uptime: 'Uptime',
    reboot_system: 'Reboot System',
    secure_portal: 'Secure User Portal',
    no_config: 'No configuration available',
    contact_admin: 'Contact administrator.',
    // Common (reused across sections)
    refresh: 'Refresh',
    status_active: 'Active',
    status_expired: 'Expired',
    status_suspended: 'Suspended',
    unknown: 'Unknown',
    edit: 'Edit',
    delete: 'Delete',
    // Users section
    user_management: 'Operator Management',
    system_access_control: 'System Access Control',
    search_operator: 'Search an operator...',
    create_access: 'Create Access',
    col_identity: 'Operator Identity',
    col_role: 'System Role',
    col_status: 'Status',
    col_action: 'Action',
    edit_operator: 'Edit Operator',
    delete_operator: 'Delete Operator',
    no_operator_found: 'No operator found',
    role_admin_label: 'Root Access',
    role_manager_label: 'Manager Access',
    role_viewer_label: 'Operator Access',
    role_admin_badge: 'Admin',
    role_manager_badge: 'Manager',
    role_viewer_badge: 'Operator',
    // Create/Edit user modals
    cancel: 'Cancel',
    optional: 'Optional',
    username_required: 'Username required',
    username_invalid: 'Invalid username (2-64 chars, letters, digits, _ and - only)',
    password_min: 'Password: 8 characters minimum',
    passwords_mismatch: 'Passwords do not match',
    create_error: 'Creation error',
    update_error: 'Update error',
    role_viewer_desc: 'Read-only',
    role_manager_desc: 'Client management',
    role_admin_desc: 'Full access',
    create_operator_title: 'Create Operator',
    create_operator_btn: 'Create Operator',
    edit_operator_title: 'Edit Operator',
    save: 'Save',
    field_username: 'Username',
    field_password: 'Password',
    field_confirm_password: 'Confirm Password',
    placeholder_username: 'e.g. operator01',
    password_leave_empty: 'Leave empty to keep unchanged',
    confirm_new_password: 'Confirm new password',
    account_active: 'Active Account',
    account_suspended: 'Suspended Account',
    reset_2fa: 'Reset 2FA (TOTP)',
    resetting: 'Resetting...',
    reset_2fa_ok: '2FA secret reset',
    reset_2fa_err: '2FA reset error',
    reset_2fa_confirm:
      'Reset 2FA for this operator? They will be able to log in again without their current code.',
    expiry: 'Expiry',
    identity_locked: 'Locked Identity',
    access_level: 'Access Level',
    expiry_date: 'Expiry Date',
    remove_expiry: 'Remove expiry',
    account_status: 'Account Status',
    suspended_hint: 'The user will not be able to log in until reactivated.',
    new_password: 'New Password',
    // Containers section
    create: 'Create',
    unlimited: 'Unlimited',
    status_online: 'Online',
    status_offline: 'Offline',
    search_placeholder: 'Search...',
    deselect_all: 'Deselect all',
    select: 'Select',
    deselect: 'Deselect',
    selected: 'selected',
    peers: 'peers',
    export_csv: 'Export CSV',
    new_peer: 'New Peer',
    new_container: 'New Container',
    col_name: 'Name',
    col_container: 'Container',
    peer_active: 'Peer online',
    peer_offline: 'Peer offline',
    expiring_soon: 'Soon',
    quota_usage: 'Quota Usage',
    disable: 'Disable',
    enable: 'Enable',
    disable_peer: 'Disable peer',
    enable_peer: 'Enable peer',
    qr_config: 'Configuration / QR Code',
    show_qr: 'Show QR Code configuration',
    delete_peer: 'Delete peer',
    modify: 'Edit',
    never: 'Never',
    daily_quota: 'Daily quota',
    data_total: 'Total Data',
    burst_dl: 'Burst DL',
    burst_ul: 'Burst UL',
    realtime: 'Real-time',
    masked_na: 'Masked / N/A',
    delete_container: 'Delete container',
    total_volume: 'Total Volume',
    no_results: 'No results',
    empty_container: 'Empty Container',
    no_peers_in_container: 'No peer in this container',
    reconcile_error: 'Reconciliation error',
    peers_reapplied: 'Peers re-applied in the tunnel',
    resync_failed: 'Resync failed',
    rescan: 'Rescan',
    no_match: 'No peer matches',
    delete_peers_first: 'Delete the peers first',
    resync_peers: 'Resync the peers',
    purge: 'Purge',
    ghosts: 'ghost(s)',
    ghosts_purged: 'ghost entry(ies) purged',
    desync_detected: 'Desync detected',
    orphans_desc: 'client(s) in DB with no file on disk (ghosts).',
    missing_desc: 'client(s) with OK files but missing from the WireGuard tunnel.',
    last_activity: 'Last activity',
    hours_72: '72 Hours',
    network_spectrum: 'Network Spectrum',
    blackbox_log: 'Blackbox Log',
    scanning_logs: 'Scanning logs...',
    no_logs: 'No logs found',
    detected_active: 'DETECTED / ACTIVE',
    inactive: 'INACTIVE',
    real_ip: 'Real IP (Endpoint)',
    real_handshake: 'Real Handshake',
    // Additional common
    loading: 'Loading…',
    // Settings section
    settings_core_title: 'Core Settings',
    tab_core: 'Core',
    tab_security: 'Security',
    tab_billing: 'Billing',
    tab_terminal: 'Terminal',
    apply_mission: 'Apply Mission',
    pending_changes: 'Pending changes',
    unsaved_changes: 'Unsaved changes',
    err_port_invalid: 'Invalid port (1–65535)',
    err_mtu_invalid: 'Invalid MTU (576–9000)',
    err_keepalive_invalid: 'Invalid keepalive (0–3600s)',
    fix_errors_before_save: 'Fix errors before saving',
    config_applied_ok: 'Configuration applied successfully',
    config_apply_err: 'Error while applying',
    backup_created_ok: 'Backup created successfully',
    backup_err: 'Backup error',
    tt_udp_port: 'Standard WireGuard listening port',
    tt_keepalive:
      'Keeps sessions alive through strict NAT firewalls via UDP stimulation (0 = disabled).',
    keepalive_reco: 'Recommended: 25s (Standard), 5s (Ultra-Stable Mobile Gaming).',
    tt_wg_endpoint:
      'Domain or public IP written in the VPN clients .conf file. Must point to this server (UDP port above).',
    ph_wg_endpoint: 'e.g. vpn.mydomain.com or 1.2.3.4',
    endpoint_warn_1: 'Only',
    endpoint_warn_new: 'new',
    endpoint_warn_2: 'clients generated after the change will use this endpoint.',
    tt_dns: 'DNS servers pushed to clients',
    tt_subnet: 'Internal IP range of the vpn tunnel',
    sec_encryption_desc:
      'ChaCha20-Poly1305 protocol active. Automatic rotation of Curve25519 session keys.',
    sec_analyze_integrity: 'Analyze Integrity',
    sec_packet_desc:
      'UFW firewall enabled. Immediate rejection of unauthorized ICMP packets and stealth SYN scans.',
    sec_firewall_logs: 'Firewall Logs',
    sec_telegram_desc:
      'Check connectivity with your Telegram bot. The system sends critical alerts on breach attempts or interface disconnection.',
    telegram_test_ok: 'Test notification sent successfully',
    telegram_test_err: 'Telegram connection failed',
    test_connection: 'Test Connection',
    maint_archives_desc:
      'Full cluster export: certificates, interface configurations and encrypted SQL database.',
    maint_generate_backup: 'Generate Backup .tar.gz',
    maint_reset_desc: 'Full architecture reset. Irreversible loss of all vpn routes.',
    maint_factory_reset: 'Restore Factory Defaults',
    // Billing
    configured_badge: 'configured',
    secret_keep_placeholder: '•••••••• (leave empty to keep)',
    settings_load_err: 'Error loading settings',
    settings_saved: 'Settings saved',
    settings_save_err: 'Save error',
    billing_stripe_title: 'Stripe — Auto renewal',
    billing_stripe_desc_1:
      'Top-level resellers buy their credits via Stripe Checkout (1 credit = 30 days of license for 1 server — renewal debits the wallet automatically). Configure the Stripe webhook URL at',
    billing_stripe_desc_2: 'Without Stripe, the contact below is shown to resellers.',
    f_stripe_secret: 'Stripe secret key',
    f_stripe_webhook: 'Webhook secret',
    f_stripe_publishable: 'Publishable key',
    f_stripe_price_id: 'Price ID',
    f_credit_price: 'Price of 1 credit (cents)',
    ph_credit_price: 'e.g. 1500 = 15.00 €',
    f_currency: 'Currency (ISO)',
    billing_platform: 'Platform',
    f_terms_url: 'Terms URL (required at signup if set)',
    f_update_paused: 'Fleet update pause (1 = frozen)',
    billing_payment_contact: 'Payment contact',
    billing_payment_contact_desc:
      'Shown to resellers to renew when Stripe is not active (manual payment via WhatsApp/Telegram).',
    f_telegram_contact: 'Telegram (contact)',
    f_payment_instructions: 'Payment instructions',
    ph_payment_instructions: 'e.g. Wire / PayPal — 15€/month per VPS',
    billing_telegram_bot: 'Telegram Bot (alerts)',
    f_bot_token: 'Bot token',
    // Optimization
    optim_reactivated: 'Optimization re-enabled',
    optim_disabled: 'System optimizations disabled (Tunnel preserved)',
    optim_toggle_err: 'SRE toggle failed',
    optim_profile_prefix: 'Profile',
    optim_profile_activated: 'activated successfully',
    optim_sync_err: 'Neural synchronization failed',
    optim_streaming_desc: 'Maximum throughput. BBR optimization & MTU 1280.',
    optim_auto_desc: 'Heuristic analysis & dynamic MTU adjustment.',
    optim_sync_desc:
      'Heuristic maintenance of the system kernel active. Real-time monitoring of memory leaks.',
    optim_system_optimized: 'System Optimized',
    optim_active_vector: 'Active Vector',
    optim_active: 'Optimization Active',
    optim_activate_profile: 'Activate Profile',
    // Dashboard
    quota_critical_suffix: 'in Critical Quota',
    manage: 'Manage',
    dash_active_protocol: 'Active Protocol',
    dash_active_peers: 'Active Peers',
    dash_connected: 'CONNECTED',
    dash_port_link: 'Link Port',
    subscribers: 'Subscribers',
    expire_soon_days: 'Expire ≤ 7 d',
    expired_count: 'Expired',
    most_active_client: 'Most active client',
    none: 'None',
    inactive_station: 'Inactive Station',
    telemetry_system: 'SENTINEL System',
    telemetry_live: 'Live Telemetry',
    history_unavailable: 'History unavailable — real-time data active',
    init_sentinel_flux: 'Initializing Sentinel streams...',
    check_traffic_history_conn: 'Check connection to the traffic-history service',
    data_after_audit: '(Data available after the first audit cycle)',
    rt_rates_label: 'Real-time rates (5 s) · Mbit/s',
    history_24h_label: '24 h history · MB volumes',
    tactical_distribution: 'Tactical Distribution',
    no_flux_detected: 'No flux detected',
    test_running: 'Test running...',
    rerun: 'Rerun',
    run_speedtest: 'Run Flow Test',
    // Audit
    audit_title: 'Security Audit',
    integrity_index: 'Integrity Index',
    integrity_desc: 'Calculation based on kernel, firewall and software protection status.',
    critical: 'Critical',
    audit_firewall_desc: 'Check of the UFW interface and pre-configured filtering rules.',
    audit_fw_ok: 'Device Protection OK',
    audit_fw_bad: 'Possible Network Vulnerability',
    audit_ipfwd_desc: 'Status of the sysctl net.ipv4.ip_forward option required for vpn transit.',
    audit_ipfwd_ok: 'Data Transit Active',
    audit_ipfwd_bad: 'Tunnel Flow Interruption',
    audit_f2b_desc: 'Monitoring of SSH brute-force attempts and IP bans.',
    audit_f2b_ok: 'Brute-Force Defense OK',
    audit_f2b_bad: 'SSH Vulnerability Detected',
    audit_disk_desc: 'Root partition usage (SSD/NVMe) for the system cache.',
    // Logs
    system_event: 'System event',
    system_source: 'System',
    logs_cleared_ok: 'Logs cleared successfully',
    logs_clear_err: 'Error while clearing',
    ws_lost: 'Real-time connection lost — Automatic reconnection in progress...',
    docker_logs_prefix: 'Docker container logs',
    clear_all_logs_q: 'Clear all logs?',
    action_irreversible: 'This action is irreversible.',
    confirm_clear: 'Confirm clearing',
    filter_placeholder: 'Filter...',
    filter_logs_aria: 'Filter logs',
    tab_access_peers: 'Peers Access',
    log_tab_security: 'Security',
    tab_system_log: 'System Log',
    entries: 'entries',
    clear: 'Clear',
    col_event: 'Event',
    scanning_archives: 'Scanning archives...',
    no_record_found: 'No record found',
    // MainLayout
    twofa_banner_text: 'Your admin account has no 2FA enabled —',
    twofa_banner_cta: 'configure now',
    upd_phase_queued: 'Queued…',
    upd_phase_downloading: 'Downloading the bundle…',
    upd_phase_verifying: 'Integrity check…',
    upd_phase_building: 'Rebuilding services…',
    upd_phase_restarting: 'Restarting…',
    upd_restarting_services: 'Restarting services…',
    upd_installing: 'Installation in progress…',
    license_expired_msg: 'License expired — client creation is blocked. Renew to continue.',
    license_label: 'License:',
    days_remaining: 'day(s) remaining',
    license_renew_hint: 'remember to renew.',
    renew_via: 'To renew:',
    upd_failed_prefix: 'Update failed',
    upd_retry_next_cycle: 'Automatic retry on the next cycle.',
    upd_label: 'Update',
    upd_installed_reload: 'installed — reloading the panel…',
    upd_dont_close: 'Do not close this page — brief network outage (~30 s) during the restart.',
    upd_ready_confirm: 'ready — your confirmation is required to install it.',
    upd_scheduled: 'scheduled',
    upd_around: 'around',
    upd_can_advance: 'you can bring it forward.',
    upd_install_now: 'Install now',
    upd_available: 'Update available',
    upd_pending_approval: 'pending approval by the platform.',
    onboarding_add_vps: 'Add your VPS to access the rest of the platform',
    access_denied_admin: 'Access denied — section restricted to administrators',
    search: 'Search',
    surveillance_active: 'Monitoring Active',
    sentinel_offline: 'Sentinel Offline',
    dns_filtering_active: 'DNS Filtering Active',
    dns_interrupted: 'DNS Interrupted',
    all_rights_reserved: 'All rights reserved.',
    delete_client: 'Delete client',
    delete_permanently: 'Delete permanently',
    delete_empty_container: 'Delete the empty container',
    revoke_access_warning: 'This action will immediately revoke their system access.',
    from_container: 'from container',
    // StatusWidget / NavItems
    wg_restarted_ok: 'WireGuard service restarted.',
    wg_restart_error: 'Error during restart.',
    restarting_label: 'Restarting...',
    confirm: 'Confirm',
    change_language: 'Change language',
    restart_wireguard: 'Restart WireGuard',
    restart_wireguard_q: 'Restart WireGuard?',
    yes: 'Yes',
    no: 'No',
    // Auth
    login_invalid_credentials: 'Invalid credentials',
    login_too_many: 'Too many attempts. Try again later.',
    login_error: 'Connection error',
    login_step_access: 'Access',
    login_headline_1: 'Tunnel.',
    login_headline_2a: 'Yours,',
    login_headline_2b: 'alone.',
    login_tagline:
      'A control interface for your WireGuard network. Provision, monitor, close the door in one gesture — without leaving your mental terminal.',
    meta_status: 'Status',
    meta_operational: 'Operational',
    meta_latency: 'Latency',
    meta_time: 'Time',
    sovereign_edition: 'Sovereign edition',
    login_step_verification: 'Verification',
    login_step_identification: 'Identification',
    hide_label: 'Hide',
    show_label: 'Show',
    remember_session: 'Remember session',
    totp_label: 'Authenticator code',
    totp_hint: '6 digits — authenticator app',
    login_connecting: 'Connecting…',
    login_validate_code: 'Validate code',
    login_enter_tunnel: 'Enter the tunnel',
    forgot_credentials: 'Forgot your credentials?',
    contact_admin_short: 'contact admin',
    register_failed: 'Registration failed',
    register_subtitle: 'Reseller registration',
    verifying: 'Verifying…',
    invite_invalid: 'Invalid or expired invitation.',
    account_created: 'Account created! You can now sign in.',
    sign_in: 'Sign in',
    invited_by: 'Invited by',
    ph_username_simple: 'Username',
    ph_password_min8: 'Password (min 8 characters)',
    ph_email_reco: 'Email (recommended — receipts & alerts)',
    accept_terms_prefix: 'I accept the',
    terms_link_label: 'terms of service',
    creating: 'Creating…',
    create_my_account: 'Create my account',
    // Servers
    srv_status_pending: 'Pending',
    srv_status_provisioning: 'Provisioning',
    srv_status_error: 'Error',
    just_now: 'just now',
    ago_prefix: '',
    ago_suffix: 'ago',
    unit_min: 'min',
    unit_hour: 'h',
    unit_day: 'd',
    update_available_cron: 'Update available (applied by the daily cron)',
    up_to_date: 'Up to date',
    deploy_version_title: 'Deploy version',
    deploy_approved_hint: 'Only the instances approved here will receive the update (≤ 30 min).',
    select_all: 'Select all',
    instances_word: 'instance(s)',
    no_instance_enrolled: 'No instance enrolled',
    deploy_mode: 'Deployment mode',
    deploy_scheduled_title: 'Scheduled (default)',
    deploy_scheduled_desc: 'Applied automatically within ~6 h, without intervention.',
    deploy_instant_title: 'Instant',
    deploy_instant_desc: 'The instance receives it right away — its operator confirms the install.',
    cancel_deployment: 'Cancel deployment',
    cancel_deployment_title: 'Removes approval: these instances will no longer get the update',
    close: 'Close',
    push_update: 'Push the update',
    scheduled_badge: 'scheduled',
    deploy_already_scheduled: 'Deployment already scheduled',
    install_command: 'Installation command',
    oneliner_validity: 'valid 10 minutes, single use',
    oneliner_desc:
      'Paste as root on the VPS. Reinstalls or installs the instance; the server license is kept.',
    copied: 'Copied',
    copy: 'Copy',
    lic_expired: 'Expired',
    expires_today: 'Expires today',
    days_left: 'd left',
    renew_1_month: '+ 1 month',
    renew_3_months: '+ 3 months',
    renew_1_year: '+ 1 year',
    channel_stable: 'Stable',
    channel_canary: 'Canary (pilot)',
    channel_hold: 'Frozen (no updates)',
    license: 'License',
    current_status: 'Current status:',
    ph_custom_days: 'Custom duration (days)',
    apply: 'Apply',
    client_cap_label: 'Client cap (empty = unlimited)',
    ph_unlimited: 'unlimited',
    update_channel_label: 'Update channel',
    cut_unpaid: 'Cut off (unpaid)',
    uninstall_wgfux: 'Uninstall wg-fux',
    uninstall_warning:
      'Stops and removes the containers, volumes (WireGuard clients included) and the configuration on the VPS itself. Irreversible.',
    type_to_confirm_prefix: 'Type',
    type_to_confirm_suffix: 'to confirm',
    uninstalling: 'Uninstalling…',
    uninstall_permanently: 'Uninstall permanently',
    srv_load_err: 'Error loading servers',
    server_deleted: 'Server deleted',
    delete_error: 'Error while deleting',
    wgfux_uninstalled: 'wg-fux uninstalled from the VPS',
    uninstall_error: 'Error while uninstalling',
    deploy_cancelled_for: 'Deployment cancelled for',
    approved_for: 'approved for',
    deploy_error: 'Deployment error',
    server_updated: 'Server updated',
    srv_online_suffix: 'online',
    srv_unreachable_suffix: 'unreachable',
    probe_failed: 'Probe failed',
    servers_deleted_suffix: 'server(s) deleted',
    licenses_extended_suffix: 'license(s) extended',
    bulk_action_failed: 'Bulk action failed',
    oneliner_gen_error: 'One-liner generation error',
    license_cut: 'License cut off',
    update_channel_prefix: 'Update channel:',
    client_cap_removed: 'Client cap removed',
    cap_prefix: 'Cap:',
    clients_word: 'client(s)',
    license_extended_until: 'License extended until',
    renew_error: 'Error while renewing',
    srv_filter_ph: 'Filter (name, host, status…)',
    deploy_btn: 'Deploy',
    add_vps: 'Add a VPS',
    licenses_7d: 'Licenses ≤ 7 d',
    clients_fleet: 'Clients (fleet)',
    pending_updates: 'Pending updates',
    extend_licenses: 'Extend licenses',
    days_to_add: 'Days to add',
    col_server: 'Server',
    col_address: 'Address',
    col_load: 'Load',
    col_version: 'Version',
    col_license: 'License',
    col_last_contact: 'Last contact',
    view_detail: 'View details',
    unnamed: 'Unnamed',
    channel_word: 'channel',
    probe_now: 'Probe now (SSH)',
    edit_meta_alerts: 'Edit (metadata, alerts)',
    install_command_oneliner: 'Installation command (one-liner)',
    manage_license: 'Manage the license',
    uninstall_from_vps: 'Uninstall wg-fux from the VPS',
    delete_server: 'Delete the server',
    no_server_matches_filter: 'No server matches the filter',
    no_server_registered: 'No server registered',
    add_first_vps: '+ Add your first VPS',
    edit_server: 'Edit the server',
    f_label: 'Label',
    f_host: 'Host',
    f_ssh_port: 'SSH Port',
    f_region: 'Region',
    f_provider: 'Provider',
    f_tags_csv: 'Tags (comma-separated)',
    f_notes: 'Notes',
    alerts_empty_disabled: 'Alerts (empty = disabled)',
    f_offline_minutes: 'Offline > N minutes',
    f_license_days: 'License < N days',
    no_history_yet: 'No history collected yet.',
    availability: 'Availability',
    points: 'points',
    probe: 'Probe',
    last_error: 'Last error',
    disk: 'Disk',
    telemetry_from: 'telemetry from',
    clients_label: 'Clients',
    target_server: 'Target server',
    this_server: 'This server',
    no_server_online: 'No server online. Register a VPS in the Servers tab.',
    // Network
    reason_topup: 'Top-up',
    reason_topup_stripe: 'Stripe purchase',
    reason_transfer_in: 'Received',
    reason_transfer_out: 'Sent',
    reason_monthly: 'Monthly debit',
    reason_client_renewal: 'Client renewal',
    reason_license_renewal: 'License renewal',
    reason_refund: 'Refund',
    net_load_err: 'Error loading the network',
    subreseller_created: 'Sub-reseller created',
    err_creation: 'Creation error',
    credits_transferred: 'Credits transferred',
    err_transfer: 'Transfer error',
    account_credited: 'Account credited',
    err_topup: 'Top-up error',
    err_payment: 'Payment error',
    sell_price_saved: 'Sell price saved',
    err_price: 'Price error',
    brand_saved: 'Brand saved',
    err_brand: 'Brand error',
    payment_contact_saved: 'Payment contact saved',
    err_contact: 'Contact error',
    err_reset: 'Reset error',
    email_of: 'Email of',
    email_updated: 'Email updated',
    net_subtitle: 'Credits · Resellers · Margin',
    balance: 'Balance',
    low: 'Low',
    credits_word: 'credits',
    margin: 'Margin',
    resale_minus_acquisition: 'resale − acquisition',
    subresellers: 'Sub-resellers',
    linked_accounts: 'linked accounts',
    buy_credits: 'Buy credits',
    buy_credits_desc:
      '1 credit = 30 days of license for 1 server. Renewal debits the wallet automatically. Sub-resellers buy from their parent reseller.',
    ph_credits_count: 'number of credits',
    pay_by_card: 'Pay by card',
    my_sell_price: 'My sell price',
    my_sell_price_desc:
      'Price charged to your network for 1 credit (in cents). Your margin = resale − acquisition.',
    ph_cents_per_credit: 'cents / credit',
    topup_account: 'Credit an account (top-up)',
    ph_credits: 'credits',
    ph_price_per_credit: 'price/credit (cents)',
    credit_btn: 'Credit',
    my_network: 'My network',
    ph_search_network: 'Search (name, email, #id)…',
    col_account: 'Account',
    col_balance: 'Balance',
    col_clients: 'Clients',
    col_license_soon: 'License soon',
    col_sell_price: 'Sell price',
    col_actions: 'Actions',
    subreseller_word: 'sub-reseller',
    reseller_word: 'reseller',
    disabled_status: 'Disabled',
    online_suffix: 'online',
    expired_short: 'Expired',
    ph_cents: 'cents',
    price_updated: 'Price updated',
    edit_sell_price: 'Edit the sell price',
    transfer_btn: 'Transfer',
    prefill_transfer: 'Pre-fill the credit transfer',
    prefill_topup: 'Pre-fill the top-up',
    edit_email: 'Edit the email',
    reset_password: 'Reset the password',
    account_disabled_msg: 'Account disabled',
    account_reenabled_msg: 'Account re-enabled',
    cut_account_access: 'Cut this account’s access',
    restore_access: 'Restore access',
    no_account_matches: 'No account matches',
    no_subreseller: 'No sub-reseller',
    page_word: 'Page',
    accounts_word: 'accounts',
    prev_short: 'Prev.',
    next_short: 'Next',
    new_subreseller: 'New sub-reseller',
    ph_password_min: 'password (min 8)',
    ph_sell_price_opt: 'sell price/credit (cents, opt.)',
    transfer_credits: 'Transfer credits',
    ph_recipient_userid: 'recipient userId',
    payment_contact: 'Payment contact',
    payment_contact_desc:
      'Shown to the clients of an instance when the license expires (manual sale without Stripe).',
    ph_whatsapp: 'WhatsApp (+33…)',
    ph_telegram: 'Telegram (@handle)',
    ph_payment_instructions_short: 'Payment instructions…',
    brand_white_label: 'Brand (white-label)',
    ph_brand_name: 'Brand name',
    ph_logo_url: 'Logo URL (https://…)',
    ph_brand_color: 'Color (#RRGGBB)',
    ph_custom_domain: 'Custom domain (vpn.example.com)',
    credits_ledger: 'Credits ledger',
    all_movements: 'All movements',
    ph_ref: 'Ref…',
    col_movement: 'Movement',
    col_credits: 'Credits',
    col_price: 'Price',
    col_ref: 'Ref.',
    no_movement: 'No movement',
    password_reset_title: 'Password reset',
    password_reset_hint_1: 'Pass it on to',
    password_reset_hint_2: 'It will not be shown again.',
    invite_active: 'Active',
    invite_used: 'Used',
    invitations: 'Invitations',
    generate_link: 'Generate a link',
    link_generated_copied: 'Link generated and copied (valid 7 days)',
    err_invite: 'Invitation error',
    invite_revoked: 'Invitation revoked',
    err_revoke: 'Revocation error',
    col_created: 'Created',
    col_expires: 'Expires',
    col_used_by: 'Used by',
    revoke: 'Revoke',
    no_invitation: 'No invitation',
    activity_12m: 'Activity (12 months)',
    cumulative_margin: 'Cumulative margin',
    credits_resold: 'Credits resold',
    acquired: 'Acquired',
    resold: 'Resold',
    consumed: 'Consumed',
    // Sales
    reason_transfer_in_credits: 'Credits received',
    reason_transfer_out_credits: 'Credits sent',
    expired_prefix: 'Expired',
    renew_30d: '+30 d',
    renew_90d: '+90 d',
    extended_until: 'extended until',
    credits_short: 'credit(s)',
    renewal_error: 'Renewal error',
    sales_subtitle: 'Subscriptions · Renewals · Credits',
    ph_filter_client: 'Filter a client…',
    credits_balance: 'Credits balance',
    subscriptions: 'Subscriptions',
    subscription: 'Subscription',
    due_on: 'Due on',
    no_expiration: 'No expiration',
    unlimited_cap: 'Unlimited cap',
    credits_title: 'Credits',
    remaining: 'remaining',
    used_word: 'used',
    included: 'included',
    pricing_note_1: 'Pricing:',
    pricing_note_2: '30 days = 1 credit',
    pricing_note_3:
      '. Collect payment from your client however you want, then renew here — credits are bought from your supplier.',
    col_client: 'Client',
    col_subscription: 'Subscription',
    col_state: 'State',
    col_renew: 'Renew',
    cut_off: 'Cut off',
    free_admin: 'Free (admin)',
    credits_unit_short: 'cr',
    no_subscription_hint: 'No subscription — create clients in Containers',
    // DNS
    dns_upstream_title: 'Upstream DNS Servers',
    dns_upstream_desc:
      'Enter one server per line. These servers will be used by AdGuard to resolve your clients requests. Prefer DoH or DoT servers for maximum security.',
    dns_bootstrap_desc:
      'These servers are used to resolve the hostnames of the upstream DNS (e.g. dns.cloudflare.com).',
    dns_filtering_label: 'AdGuard Filtering',
    dns_filtering_desc: 'Enables ad and tracking blocking.',
    dns_safebrowsing_label: 'Safe Browsing',
    dns_safebrowsing_desc: 'Blocks malicious and phishing sites.',
    dns_parental_label: 'Parental Control',
    dns_parental_desc: 'Blocks adult content.',
    dns_safesearch_desc: 'Forces safe mode on Google, YouTube, etc.',
    blocklists: 'blocklists',
    rules: 'rules',
    ph_filter_blocklists: 'Filter blocklists…',
    delete_blocklist: 'Delete this blocklist',
    no_blocklist_matches: 'No blocklist matches',
    no_blocklist_configured: 'No blocklist configured',
    quick_add: 'Quick add',
    add_custom_blocklist: 'Add a custom blocklist',
    ph_blocklist_name: 'Name (e.g. Steven Black)',
    ph_blocklist_url: 'URL (https://…)',
    add: 'Add',
    invalid_url: 'Invalid URL (expected: https://…)',
    blocklist_already_added: 'This blocklist is already added.',
    adguard_load_err: 'Unable to load AdGuard Home data',
    config_partially_applied: 'Configuration partially applied',
    dns_config_updated: 'DNS configuration updated successfully',
    dns_save_err: 'Error while saving the configuration',
    blocklist_added: 'Blocklist added',
    add_error: 'Error while adding',
    blocklist_removed: 'Blocklist removed',
    dns_init: 'DNS initialization...',
    dns_center: 'DNS Center',
    adguard_engine_active: 'AdGuard engine active',
    no_change: 'No change',
    deploying: 'Deploying...',
    apply_changes: 'Apply changes',
    saved: 'Saved',
    dns_queries: 'Queries',
    dns_blocked: 'Blocked',
    last_24h: 'Last 24h',
    dns_latency: 'Latency',
    average: 'Average',
    // User report
    period_day: 'Day',
    period_week: 'Week',
    period_month: 'Month',
    chart_creations_24h: 'Creations — last 24 hours',
    chart_creations_7d: 'Creations — last 7 days',
    chart_creations_30d: 'Creations — last 30 days',
    activity_24h: '24h',
    activity_7d: '7 days',
    activity_30d: '30 days',
    added_24h: 'Added 24h',
    added_7d: 'Added 7d',
    added_30d: 'Added 30d',
    added_generic: 'Added',
    report_title: 'Report',
    expires_word: 'expires',
    clients_total: 'Total clients',
    actives: 'Active',
    recent_activity: 'Recent activity',
    no_peer_dot: 'No peer.',
    no_activity_recorded: 'No activity recorded',
    report_load_err: 'Unable to load the report',
    server_online: 'Server online',
    err_label_required: 'Label required',
    err_host_required: 'Host / IP required',
    err_port_range: 'Invalid port (1-65535)',
    register_error: 'Error while registering',
    copy_failed: 'Copy failed',
    ph_vps_label: 'e.g. vps-paris-01',
    f_host_ip: 'Host / IP',
    ph_host_ip: 'e.g. 203.0.113.10',
    register_vps: 'Register the VPS',
    provisioning_command: 'Provisioning command',
    paste_command_hint: 'Paste this command as root on your VPS, then wait ~30s.',
    provisioning_failed: 'Provisioning failed',
    command_expired: 'Command expired — regenerate it',
    waiting_for_server: 'Waiting for the server…',
    later: 'Later',
    regenerate_command: 'Regenerate the command',
    done: 'Done',
    copy_command: 'Copy the command',
    vps_provisioning: 'VPS provisioning',
    // Client / container modals
    client_name_invalid: 'Invalid name (1-64 characters, letters, digits, _ and - only)',
    invalid_duration: 'Please enter a valid validity duration',
    peer_created_ok: 'created successfully',
    name_already_used_1: "The name '",
    name_already_used_2: "' is already in use",
    client_create_err: 'Error while creating the client',
    peer_init_title: 'Peer Initialization',
    f_client_name: 'Client Name',
    ph_client_name: 'e.g. galaxy-s24',
    f_tactical_group: 'Tactical Group (Container)',
    select_container_opt: '— Select a container —',
    container_target_hint_current: 'The client will be added to this current container.',
    container_target_hint_choose: 'Choose the destination container.',
    f_time_validity: 'Time validity',
    unit_days: 'Days',
    unit_hours: 'Hours',
    f_data_quota: 'Data Quota',
    f_bandwidth: 'Bandwidth',
    cancel_mission: 'Cancel Mission',
    init_peer_access: 'Initialize Peer access',
    peer_updated_ok: 'updated successfully',
    edit_peer_title: 'Edit Peer',
    aria_quota_gb: 'Quota in GB',
    aria_quota_slider: 'Data quota (slider)',
    unlimited_paren: '0 (unlimited)',
    f_max_bandwidth: 'Max Bandwidth',
    aria_upload_limit: 'Upload limit in Mbps',
    aria_bandwidth_slider: 'Max bandwidth (slider)',
    aria_unlimited_on: 'Unlimited duration enabled',
    aria_unlimited_off: 'Unlimited duration disabled',
    save_btn: 'Save',
    confirm_delete_title: 'Confirm deletion',
    permanent_action_warning: 'This action is permanent and cannot be undone.',
    new_container_title: 'New Container',
    f_container_name: 'Container Name (Group)',
    ph_container_name: 'e.g. family, servers',
    container_name_hint: 'Letters, digits, dashes and underscores only.',
    download_conf: 'Download .conf',
    // Misc: global search, SRE monitoring, network node, error boundaries
    gs_navigation: 'Navigation',
    gs_peers_section: 'Peers',
    gs_search_placeholder: 'Search peers, sections, IP...',
    gs_hint: 'Peers · Sections · IP addresses',
    gs_dashboard_desc: 'Real-time statistics',
    gs_containers_desc: 'WireGuard peer management',
    gs_users_desc: 'Operator access',
    gs_logs_label: 'System Logs',
    gs_audit_desc: 'Security control',
    gs_optimization_desc: 'Network profiles',
    gs_settings_desc: 'System configuration',
    perf_fetch_error: 'Failed to fetch telemetry',
    perf_conn_error: 'Connection error',
    perf_optimal: 'Optimal',
    perf_nominal: 'Nominal',
    perf_congested: 'Congested',
    perf_jitter: 'Jitter',
    perf_load: 'Load',
    perf_bloat: 'Bloat',
    nn_tact_ip: 'Tactical IP',
    nn_endpoint: 'Endpoint',
    nn_total_usage: 'Total usage',
    nn_last_seen: 'Last seen',
    if_fetch_error: 'Failed to fetch interfaces',
    version: 'Version',
    eb_component: 'Component',
    eb_unexpected: 'An unexpected error occurred.',
    geb_title: 'Corrupted Interface',
    geb_unknown: 'Unknown Error',
    geb_desc: 'An unexpected error crashed the interface. VPN services are NOT affected.',
    geb_reset: 'Reset Interface',
    eb_critical_error: 'Critical Error',
    stack_trace: 'Stack Trace',
    reset: 'Reset',
    gs_logs_desc: 'Access and security logs',
    tactical_groups: 'Tactical Groups',
  },
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(localStorage.getItem('app-lang') || 'fr');

  useEffect(() => {
    localStorage.setItem('app-lang', lang);
  }, [lang]);

  const t = (key) => {
    return translations[lang]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>{children}</LanguageContext.Provider>
  );
};

export const useLang = () => useContext(LanguageContext);

// Traduction HORS React (composants classe, error boundaries). N'utilise ni hook
// ni contexte : une error boundary s'affiche justement quand l'arbre React est
// cassé — dépendre du contexte y serait fragile. Lit la langue dans localStorage.
export const translate = (key) => {
  let lang = 'fr';
  try {
    lang = localStorage.getItem('app-lang') || 'fr';
  } catch {
    /* localStorage indisponible : on retombe sur le français */
  }
  return translations[lang]?.[key] ?? translations.fr?.[key] ?? key;
};
