import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  fr: {
    dashboard: 'Tableau de bord',
    containers: 'Conteneurs',
    sales: 'Ventes',
    network: 'Réseau',
    users_manage: 'Utilisateurs',
    servers: 'Serveurs',
    logs: 'Logs',
    topology: 'Topologie',
    dns_editor: 'Éditeur DNS',
    optimization: 'Optimisation',
    audit: 'Audit',
    settings: 'Paramètres',
    logout: 'Déconnexion',
    configs: 'Configurations',
    support: 'Support',
    active_core: 'Cœur Actif',
    uptime: 'Temps Activité',
    reboot_system: 'Redémarrer Système',
    secure_portal: 'Espace Utilisateur Sécurisé',
    no_config: 'Aucune configuration disponible',
    contact_admin: "Contactez l'administrateur.",
    // Communs (réutilisés dans toutes les sections)
    refresh: 'Actualiser',
    status_active: 'Actif',
    status_expired: 'Expiré',
    status_suspended: 'Suspendu',
    unknown: 'Inconnu',
    edit: 'Éditer',
    delete: 'Supprimer',
    // Section Utilisateurs
    user_management: 'Gestion des Opérateurs',
    system_access_control: "Contrôle d'accès système",
    search_operator: 'Rechercher un opérateur...',
    create_access: 'Créer un Accès',
    col_identity: 'Identité Opérateur',
    col_role: 'Rôle Système',
    col_status: 'Statut',
    col_action: 'Intervention',
    edit_operator: 'Éditer Opérateur',
    delete_operator: 'Supprimer Opérateur',
    no_operator_found: 'Aucun opérateur trouvé',
    role_admin_label: 'Accès Root',
    role_manager_label: 'Accès Manager',
    role_viewer_label: 'Accès Opérateur',
    role_admin_badge: 'Admin',
    role_manager_badge: 'Manager',
    role_viewer_badge: 'Opérateur',
    // Modales Créer/Éditer utilisateur
    cancel: 'Annuler',
    optional: 'Optionnel',
    username_required: "Nom d'utilisateur requis",
    username_invalid:
      "Nom d'utilisateur invalide (2-64 caractères, lettres, chiffres, _ et - uniquement)",
    password_min: 'Mot de passe : 8 caractères minimum',
    passwords_mismatch: 'Les mots de passe ne correspondent pas',
    create_error: 'Erreur lors de la création',
    update_error: 'Erreur lors de la mise à jour',
    role_viewer_desc: 'Lecture seule',
    role_manager_desc: 'Gestion Clients',
    role_admin_desc: 'Accès complet',
    create_operator_title: 'Créer un Opérateur',
    create_operator_btn: "Créer l'Opérateur",
    edit_operator_title: "Éditer l'Opérateur",
    save: 'Enregistrer',
    field_username: 'Identifiant',
    field_password: 'Mot de Passe',
    field_confirm_password: 'Confirmer le Mot de Passe',
    placeholder_username: 'ex: operateur01',
    password_leave_empty: 'Laisser vide pour inchangé',
    confirm_new_password: 'Confirmer nouveau mot de passe',
    account_active: 'Compte Actif',
    account_suspended: 'Compte Suspendu',
    reset_2fa: 'Réinitialiser 2FA (TOTP)',
    resetting: 'Réinitialisation...',
    reset_2fa_ok: 'Secret 2FA réinitialisé',
    reset_2fa_err: 'Erreur reset 2FA',
    reset_2fa_confirm:
      'Réinitialiser le 2FA pour cet opérateur ? Il pourra se reconnecter sans son code actuel.',
    expiry: 'Expiration',
    identity_locked: 'Identité Verrouillée',
    access_level: "Niveau d'Accès",
    expiry_date: "Date d'Expiration",
    remove_expiry: "Supprimer l'expiration",
    account_status: 'Statut du Compte',
    suspended_hint: "L'utilisateur ne pourra plus se connecter jusqu'à réactivation.",
    new_password: 'Nouveau Mot de Passe',
    // Section Conteneurs
    create: 'Créer',
    unlimited: 'Illimité',
    status_online: 'En ligne',
    status_offline: 'Hors ligne',
    search_placeholder: 'Rechercher...',
    deselect_all: 'Désélectionner tout',
    select: 'Sélectionner',
    deselect: 'Désélectionner',
    selected: 'sélectionné(s)',
    peers: 'peers',
    export_csv: 'Exporter CSV',
    new_peer: 'Nouveau Peer',
    new_container: 'Nouveau Conteneur',
    col_name: 'Nom',
    col_container: 'Conteneur',
    peer_active: 'Peer actif',
    peer_offline: 'Peer hors ligne',
    expiring_soon: 'Bientôt',
    quota_usage: 'Utilisation Quota',
    disable: 'Désactiver',
    enable: 'Activer',
    disable_peer: 'Désactiver le peer',
    enable_peer: 'Activer le peer',
    qr_config: 'Configuration / QR Code',
    show_qr: 'Afficher la configuration QR Code',
    delete_peer: 'Supprimer le peer',
    modify: 'Modifier',
    never: 'Jamais',
    daily_quota: 'Quota journalier',
    data_total: 'Données Totales',
    burst_dl: 'Burst DL',
    burst_ul: 'Burst UL',
    realtime: 'Temps réel',
    masked_na: 'Masquée / N/A',
    delete_container: 'Supprimer le conteneur',
    total_volume: 'Volume Total',
    no_results: 'Aucun résultat',
    empty_container: 'Conteneur Vide',
    no_peers_in_container: 'Aucun peer dans ce conteneur',
    reconcile_error: 'Erreur de réconciliation',
    peers_reapplied: 'Peers ré-appliqués dans le tunnel',
    resync_failed: 'Échec de la resynchronisation',
    rescan: 'Ré-analyser',
    no_match: 'Aucun peer ne correspond à',
    delete_peers_first: "Supprimez d'abord les peers",
    resync_peers: 'Resynchroniser les peers',
    purge: 'Purger',
    ghosts: 'fantôme(s)',
    ghosts_purged: 'entrée(s) fantôme(s) purgée(s)',
    desync_detected: 'Désynchronisation détectée',
    orphans_desc: 'client(s) en base sans fichier sur le disque (fantômes).',
    missing_desc: 'client(s) avec fichiers OK mais absent(s) du tunnel WireGuard.',
    last_activity: 'Dernière activité',
    hours_72: '72 Heures',
    network_spectrum: 'Spectre Réseau',
    blackbox_log: 'Blackbox Log',
    scanning_logs: 'Analyse des logs...',
    no_logs: 'Aucun log',
    detected_active: 'DÉTECTÉ / ACTIF',
    inactive: 'INACTIF',
    real_ip: 'IP Réelle (Endpoint)',
    real_handshake: 'Handshake Réel',
    // Communs additionnels
    loading: 'Chargement…',
    // Section Paramètres
    settings_core_title: 'Paramètres Noyau',
    tab_core: 'Noyau',
    tab_security: 'Sûreté',
    tab_billing: 'Facturation',
    tab_terminal: 'Terminal',
    apply_mission: 'Appliquer Mission',
    pending_changes: 'Modifications en attente',
    unsaved_changes: 'Modifications non sauvegardées',
    err_port_invalid: 'Port invalide (1–65535)',
    err_mtu_invalid: 'MTU invalide (576–9000)',
    err_keepalive_invalid: 'Keepalive invalide (0–3600s)',
    fix_errors_before_save: 'Corriger les erreurs avant de sauvegarder',
    config_applied_ok: 'Configuration appliquée avec succès',
    config_apply_err: "Erreur lors de l'application",
    backup_created_ok: 'Sauvegarde créée avec succès',
    backup_err: 'Erreur lors du backup',
    tt_udp_port: "Port d'écoute standard WireGuard",
    tt_keepalive:
      'Maintient les sessions actives à travers les pare-feu NAT rigides via stimulation UDP (0 = désactivé).',
    keepalive_reco: 'Recommandé : 25s (Standard), 5s (Gaming Mobile Ultra-Stable).',
    tt_wg_endpoint:
      'Domaine ou IP publique inscrit dans le fichier .conf des clients VPN. Doit pointer vers ce serveur (port UDP ci-dessus).',
    ph_wg_endpoint: 'ex: vpn.mondomaine.com ou 1.2.3.4',
    endpoint_warn_1: 'Seuls les',
    endpoint_warn_new: 'nouveaux',
    endpoint_warn_2: "clients générés après la modification utiliseront ce point d'entrée.",
    tt_dns: 'Serveurs DNS transmis aux clients',
    tt_subnet: "Plage d'IP interne du tunnel vpn",
    sec_encryption_desc:
      'Protocole ChaCha20-Poly1305 actif. Rotation automatique des clés de session Curve25519.',
    sec_analyze_integrity: 'Analyser Intégrité',
    sec_packet_desc:
      'Pare-feu UFW activé. Rejet immédiat des paquets ICMP non autorisés et scans SYN furtifs.',
    sec_firewall_logs: 'Logs Firewall',
    sec_telegram_desc:
      "Vérifiez la connectivité avec votre bot Telegram. Le système envoie des alertes critiques lors des tentatives de brèche ou de déconnexion d'interface.",
    telegram_test_ok: 'Notification de test envoyée avec succès',
    telegram_test_err: 'Échec de la connexion Telegram',
    test_connection: 'Tester la Connexion',
    maint_archives_desc:
      "Exportation complète du cluster : certificats, configurations d'interfaces et database SQL cryptée.",
    maint_generate_backup: 'Générer Backup .tar.gz',
    maint_reset_desc:
      "Réinitialisation complète de l'architecture. Perte irrémédiable de toutes les routes vpn.",
    maint_factory_reset: 'Restaurer Valeurs Usine',
    // Facturation
    configured_badge: 'configuré',
    secret_keep_placeholder: '•••••••• (laisser vide pour conserver)',
    settings_load_err: 'Erreur de chargement des réglages',
    settings_saved: 'Réglages enregistrés',
    settings_save_err: "Erreur d'enregistrement",
    billing_stripe_title: 'Stripe — Renouvellement auto',
    billing_stripe_desc_1:
      "Les revendeurs top-level achètent leurs crédits par Stripe Checkout (1 crédit = 30 jours de licence pour 1 serveur — le renouvellement débite le portefeuille automatiquement). Configurez l'URL du webhook Stripe sur",
    billing_stripe_desc_2: 'Sans Stripe, le contact ci-dessous est affiché aux revendeurs.',
    f_stripe_secret: 'Clé secrète Stripe',
    f_stripe_webhook: 'Secret du webhook',
    f_stripe_publishable: 'Clé publiable',
    f_stripe_price_id: 'ID de prix (Price ID)',
    f_credit_price: "Prix d'1 crédit (centimes)",
    ph_credit_price: 'ex: 1500 = 15,00 €',
    f_currency: 'Devise (ISO)',
    billing_platform: 'Plateforme',
    f_terms_url: "URL des CGU (exigées à l'inscription si définie)",
    f_update_paused: 'Pause des mises à jour flotte (1 = gelées)',
    billing_payment_contact: 'Contact de paiement',
    billing_payment_contact_desc:
      "Affiché aux revendeurs pour renouveler quand Stripe n'est pas actif (paiement manuel via WhatsApp/Telegram).",
    f_telegram_contact: 'Telegram (contact)',
    f_payment_instructions: 'Instructions de paiement',
    ph_payment_instructions: 'ex: Virement / PayPal — 15€/mois par VPS',
    billing_telegram_bot: 'Bot Telegram (alertes)',
    f_bot_token: 'Token du bot',
    // Optimisation
    optim_reactivated: 'Optimisation réactivée',
    optim_disabled: 'Optimisations système désactivées (Tunnel préservé)',
    optim_toggle_err: 'Échec du basculement SRE',
    optim_profile_prefix: 'Profil',
    optim_profile_activated: 'activé avec succès',
    optim_sync_err: 'Échec de la synchronisation neurale',
    optim_streaming_desc: 'Throughput maximal. Optimisation BBR & MTU 1280.',
    optim_auto_desc: 'Analyse heuristique & ajustement dynamique du MTU.',
    optim_sync_desc:
      'Maintenance heuristique du noyau système active. Surveillance en temps réel des fuites mémoires.',
    optim_system_optimized: 'Système Optimisé',
    optim_active_vector: 'Vecteur Actif',
    optim_active: 'Optimisation Active',
    optim_activate_profile: 'Activer Profil',
    // Dashboard
    quota_critical_suffix: 'en Quota Critique',
    manage: 'Gérer',
    dash_active_protocol: 'Protocole Actif',
    dash_active_peers: 'Peers Actifs',
    dash_connected: 'CONNECTÉS',
    dash_port_link: 'Port Liaison',
    subscribers: 'Abonnés',
    expire_soon_days: 'Expirent ≤ 7 j',
    expired_count: 'Expirés',
    most_active_client: 'Client le plus actif',
    none: 'Aucun',
    inactive_station: 'Station Inactive',
    telemetry_system: 'Système SENTINEL',
    telemetry_live: 'Télémétrie Live',
    history_unavailable: 'Historique indisponible — données temps réel actives',
    init_sentinel_flux: 'Initialisation des flux Sentinel...',
    check_traffic_history_conn: 'Vérifier la connexion au service traffic-history',
    data_after_audit: "(Données disponibles après le premier cycle d'audit)",
    rt_rates_label: 'Débits temps réel (5 s) · Mbit/s',
    history_24h_label: 'Historique 24 h · volumes MB',
    tactical_distribution: 'Répartition Tactique',
    no_flux_detected: 'Aucun flux détecté',
    test_running: 'Test en cours...',
    rerun: 'Relancer',
    run_speedtest: 'Lancer Test de Flux',
    // Audit
    audit_title: 'Audit de Sécurité',
    integrity_index: "Indice d'Intégrité",
    integrity_desc:
      "Calcul basé sur l'état du noyau, du firewall et des protections logicielles.",
    critical: 'Critique',
    audit_firewall_desc:
      "Vérification de l'interface UFW et des règles de filtrage pré-configurées.",
    audit_fw_ok: 'Protection Périphérique OK',
    audit_fw_bad: 'Vulnérabilité Réseau Possible',
    audit_ipfwd_desc: "État de l'option sysctl net.ipv4.ip_forward nécessaire au transit vpn.",
    audit_ipfwd_ok: 'Transit de Données Actif',
    audit_ipfwd_bad: 'Interruption Flux Tunnel',
    audit_f2b_desc: 'Surveillance des tentatives de brute-force SSH et des bannissements IP.',
    audit_f2b_ok: 'Defense Brute-Force OK',
    audit_f2b_bad: 'Vulnérabilité SSH Détectée',
    audit_disk_desc: 'Utilisation de la partition racine (SSD/NVMe) pour le cache système.',
    // Logs
    system_event: 'Événement système',
    system_source: 'Système',
    logs_cleared_ok: 'Journaux effacés avec succès',
    logs_clear_err: "Erreur lors de l'effacement",
    ws_lost: 'Connexion temps réel perdue — Reconnexion automatique en cours...',
    docker_logs_prefix: 'Logs des conteneurs Docker',
    clear_all_logs_q: 'Effacer tous les journaux ?',
    action_irreversible: 'Cette action est irréversible.',
    confirm_clear: "Confirmer l'effacement",
    filter_placeholder: 'Filtrer...',
    filter_logs_aria: 'Filtrer les logs',
    tab_access_peers: 'Accès Peers',
    log_tab_security: 'Sécurité',
    tab_system_log: 'Journal Système',
    entries: 'entrées',
    clear: 'Effacer',
    col_event: 'Événement',
    scanning_archives: 'Scanning archives...',
    no_record_found: 'Aucun enregistrement détecté',
    // MainLayout
    twofa_banner_text: "Votre compte admin n'a pas de 2FA activé —",
    twofa_banner_cta: 'configurer maintenant',
    upd_phase_queued: 'En file d’attente…',
    upd_phase_downloading: 'Téléchargement du bundle…',
    upd_phase_verifying: 'Vérification d’intégrité…',
    upd_phase_building: 'Reconstruction des services…',
    upd_phase_restarting: 'Redémarrage…',
    upd_restarting_services: 'Redémarrage des services…',
    upd_installing: 'Installation en cours…',
    license_expired_msg:
      'Licence expirée — la création de clients est bloquée. Renouvelez pour continuer.',
    license_label: 'Licence :',
    days_remaining: 'jour(s) restant(s)',
    license_renew_hint: 'pensez à renouveler.',
    renew_via: 'Pour renouveler :',
    upd_failed_prefix: 'Échec de la mise à jour',
    upd_retry_next_cycle: 'Nouvelle tentative automatique au prochain cycle.',
    upd_label: 'Mise à jour',
    upd_installed_reload: 'installée — rechargement du panneau…',
    upd_dont_close: 'Ne fermez pas cette page — coupure réseau brève (~30 s) pendant le redémarrage.',
    upd_ready_confirm: "prête — votre confirmation est requise pour l'installer.",
    upd_scheduled: 'programmée',
    upd_around: 'vers',
    upd_can_advance: "vous pouvez l'avancer.",
    upd_install_now: 'Installer maintenant',
    upd_available: 'Mise à jour disponible',
    upd_pending_approval: 'en attente d’approbation par la plateforme.',
    onboarding_add_vps: 'Ajoutez votre VPS pour accéder au reste de la plateforme',
    access_denied_admin: 'Accès refusé — section réservée aux administrateurs',
    search: 'Rechercher',
    surveillance_active: 'Surveillance Active',
    sentinel_offline: 'Sentinel Hors-ligne',
    dns_filtering_active: 'Filtrage DNS Actif',
    dns_interrupted: 'DNS Interrompu',
    all_rights_reserved: 'Tous droits réservés.',
    delete_client: 'Supprimer le client',
    delete_permanently: 'Supprimer définitivement',
    delete_empty_container: 'Supprimer le conteneur vide',
    revoke_access_warning: 'Cette action révoquera immédiatement ses accès système.',
    from_container: 'du conteneur',
    // StatusWidget / NavItems
    wg_restarted_ok: 'Service WireGuard redémarré.',
    wg_restart_error: 'Erreur lors du redémarrage.',
    restarting_label: 'Redémarrage...',
    confirm: 'Confirmer',
    change_language: 'Changer de langue',
    restart_wireguard: 'Redémarrer WireGuard',
    restart_wireguard_q: 'Redémarrer WireGuard ?',
    yes: 'Oui',
    no: 'Non',
  },
  en: {
    dashboard: 'Dashboard',
    containers: 'Containers',
    sales: 'Sales',
    network: 'Network',
    users_manage: 'Users',
    servers: 'Servers',
    logs: 'Logs',
    topology: 'Topology',
    dns_editor: 'DNS Editor',
    optimization: 'Optimization',
    audit: 'Audit',
    settings: 'Settings',
    logout: 'Logout',
    configs: 'Configurations',
    support: 'Support',
    active_core: 'Active Core',
    uptime: 'Uptime',
    reboot_system: 'Reboot System',
    secure_portal: 'Secure User Portal',
    no_config: 'No configuration available',
    contact_admin: 'Contact administrator.',
    // Common (reused across sections)
    refresh: 'Refresh',
    status_active: 'Active',
    status_expired: 'Expired',
    status_suspended: 'Suspended',
    unknown: 'Unknown',
    edit: 'Edit',
    delete: 'Delete',
    // Users section
    user_management: 'Operator Management',
    system_access_control: 'System Access Control',
    search_operator: 'Search an operator...',
    create_access: 'Create Access',
    col_identity: 'Operator Identity',
    col_role: 'System Role',
    col_status: 'Status',
    col_action: 'Action',
    edit_operator: 'Edit Operator',
    delete_operator: 'Delete Operator',
    no_operator_found: 'No operator found',
    role_admin_label: 'Root Access',
    role_manager_label: 'Manager Access',
    role_viewer_label: 'Operator Access',
    role_admin_badge: 'Admin',
    role_manager_badge: 'Manager',
    role_viewer_badge: 'Operator',
    // Create/Edit user modals
    cancel: 'Cancel',
    optional: 'Optional',
    username_required: 'Username required',
    username_invalid: 'Invalid username (2-64 chars, letters, digits, _ and - only)',
    password_min: 'Password: 8 characters minimum',
    passwords_mismatch: 'Passwords do not match',
    create_error: 'Creation error',
    update_error: 'Update error',
    role_viewer_desc: 'Read-only',
    role_manager_desc: 'Client management',
    role_admin_desc: 'Full access',
    create_operator_title: 'Create Operator',
    create_operator_btn: 'Create Operator',
    edit_operator_title: 'Edit Operator',
    save: 'Save',
    field_username: 'Username',
    field_password: 'Password',
    field_confirm_password: 'Confirm Password',
    placeholder_username: 'e.g. operator01',
    password_leave_empty: 'Leave empty to keep unchanged',
    confirm_new_password: 'Confirm new password',
    account_active: 'Active Account',
    account_suspended: 'Suspended Account',
    reset_2fa: 'Reset 2FA (TOTP)',
    resetting: 'Resetting...',
    reset_2fa_ok: '2FA secret reset',
    reset_2fa_err: '2FA reset error',
    reset_2fa_confirm:
      'Reset 2FA for this operator? They will be able to log in again without their current code.',
    expiry: 'Expiry',
    identity_locked: 'Locked Identity',
    access_level: 'Access Level',
    expiry_date: 'Expiry Date',
    remove_expiry: 'Remove expiry',
    account_status: 'Account Status',
    suspended_hint: 'The user will not be able to log in until reactivated.',
    new_password: 'New Password',
    // Containers section
    create: 'Create',
    unlimited: 'Unlimited',
    status_online: 'Online',
    status_offline: 'Offline',
    search_placeholder: 'Search...',
    deselect_all: 'Deselect all',
    select: 'Select',
    deselect: 'Deselect',
    selected: 'selected',
    peers: 'peers',
    export_csv: 'Export CSV',
    new_peer: 'New Peer',
    new_container: 'New Container',
    col_name: 'Name',
    col_container: 'Container',
    peer_active: 'Peer online',
    peer_offline: 'Peer offline',
    expiring_soon: 'Soon',
    quota_usage: 'Quota Usage',
    disable: 'Disable',
    enable: 'Enable',
    disable_peer: 'Disable peer',
    enable_peer: 'Enable peer',
    qr_config: 'Configuration / QR Code',
    show_qr: 'Show QR Code configuration',
    delete_peer: 'Delete peer',
    modify: 'Edit',
    never: 'Never',
    daily_quota: 'Daily quota',
    data_total: 'Total Data',
    burst_dl: 'Burst DL',
    burst_ul: 'Burst UL',
    realtime: 'Real-time',
    masked_na: 'Masked / N/A',
    delete_container: 'Delete container',
    total_volume: 'Total Volume',
    no_results: 'No results',
    empty_container: 'Empty Container',
    no_peers_in_container: 'No peer in this container',
    reconcile_error: 'Reconciliation error',
    peers_reapplied: 'Peers re-applied in the tunnel',
    resync_failed: 'Resync failed',
    rescan: 'Rescan',
    no_match: 'No peer matches',
    delete_peers_first: 'Delete the peers first',
    resync_peers: 'Resync the peers',
    purge: 'Purge',
    ghosts: 'ghost(s)',
    ghosts_purged: 'ghost entry(ies) purged',
    desync_detected: 'Desync detected',
    orphans_desc: 'client(s) in DB with no file on disk (ghosts).',
    missing_desc: 'client(s) with OK files but missing from the WireGuard tunnel.',
    last_activity: 'Last activity',
    hours_72: '72 Hours',
    network_spectrum: 'Network Spectrum',
    blackbox_log: 'Blackbox Log',
    scanning_logs: 'Scanning logs...',
    no_logs: 'No logs found',
    detected_active: 'DETECTED / ACTIVE',
    inactive: 'INACTIVE',
    real_ip: 'Real IP (Endpoint)',
    real_handshake: 'Real Handshake',
    // Additional common
    loading: 'Loading…',
    // Settings section
    settings_core_title: 'Core Settings',
    tab_core: 'Core',
    tab_security: 'Security',
    tab_billing: 'Billing',
    tab_terminal: 'Terminal',
    apply_mission: 'Apply Mission',
    pending_changes: 'Pending changes',
    unsaved_changes: 'Unsaved changes',
    err_port_invalid: 'Invalid port (1–65535)',
    err_mtu_invalid: 'Invalid MTU (576–9000)',
    err_keepalive_invalid: 'Invalid keepalive (0–3600s)',
    fix_errors_before_save: 'Fix errors before saving',
    config_applied_ok: 'Configuration applied successfully',
    config_apply_err: 'Error while applying',
    backup_created_ok: 'Backup created successfully',
    backup_err: 'Backup error',
    tt_udp_port: 'Standard WireGuard listening port',
    tt_keepalive:
      'Keeps sessions alive through strict NAT firewalls via UDP stimulation (0 = disabled).',
    keepalive_reco: 'Recommended: 25s (Standard), 5s (Ultra-Stable Mobile Gaming).',
    tt_wg_endpoint:
      'Domain or public IP written in the VPN clients .conf file. Must point to this server (UDP port above).',
    ph_wg_endpoint: 'e.g. vpn.mydomain.com or 1.2.3.4',
    endpoint_warn_1: 'Only',
    endpoint_warn_new: 'new',
    endpoint_warn_2: 'clients generated after the change will use this endpoint.',
    tt_dns: 'DNS servers pushed to clients',
    tt_subnet: 'Internal IP range of the vpn tunnel',
    sec_encryption_desc:
      'ChaCha20-Poly1305 protocol active. Automatic rotation of Curve25519 session keys.',
    sec_analyze_integrity: 'Analyze Integrity',
    sec_packet_desc:
      'UFW firewall enabled. Immediate rejection of unauthorized ICMP packets and stealth SYN scans.',
    sec_firewall_logs: 'Firewall Logs',
    sec_telegram_desc:
      'Check connectivity with your Telegram bot. The system sends critical alerts on breach attempts or interface disconnection.',
    telegram_test_ok: 'Test notification sent successfully',
    telegram_test_err: 'Telegram connection failed',
    test_connection: 'Test Connection',
    maint_archives_desc:
      'Full cluster export: certificates, interface configurations and encrypted SQL database.',
    maint_generate_backup: 'Generate Backup .tar.gz',
    maint_reset_desc: 'Full architecture reset. Irreversible loss of all vpn routes.',
    maint_factory_reset: 'Restore Factory Defaults',
    // Billing
    configured_badge: 'configured',
    secret_keep_placeholder: '•••••••• (leave empty to keep)',
    settings_load_err: 'Error loading settings',
    settings_saved: 'Settings saved',
    settings_save_err: 'Save error',
    billing_stripe_title: 'Stripe — Auto renewal',
    billing_stripe_desc_1:
      'Top-level resellers buy their credits via Stripe Checkout (1 credit = 30 days of license for 1 server — renewal debits the wallet automatically). Configure the Stripe webhook URL at',
    billing_stripe_desc_2: 'Without Stripe, the contact below is shown to resellers.',
    f_stripe_secret: 'Stripe secret key',
    f_stripe_webhook: 'Webhook secret',
    f_stripe_publishable: 'Publishable key',
    f_stripe_price_id: 'Price ID',
    f_credit_price: 'Price of 1 credit (cents)',
    ph_credit_price: 'e.g. 1500 = 15.00 €',
    f_currency: 'Currency (ISO)',
    billing_platform: 'Platform',
    f_terms_url: 'Terms URL (required at signup if set)',
    f_update_paused: 'Fleet update pause (1 = frozen)',
    billing_payment_contact: 'Payment contact',
    billing_payment_contact_desc:
      'Shown to resellers to renew when Stripe is not active (manual payment via WhatsApp/Telegram).',
    f_telegram_contact: 'Telegram (contact)',
    f_payment_instructions: 'Payment instructions',
    ph_payment_instructions: 'e.g. Wire / PayPal — 15€/month per VPS',
    billing_telegram_bot: 'Telegram Bot (alerts)',
    f_bot_token: 'Bot token',
    // Optimization
    optim_reactivated: 'Optimization re-enabled',
    optim_disabled: 'System optimizations disabled (Tunnel preserved)',
    optim_toggle_err: 'SRE toggle failed',
    optim_profile_prefix: 'Profile',
    optim_profile_activated: 'activated successfully',
    optim_sync_err: 'Neural synchronization failed',
    optim_streaming_desc: 'Maximum throughput. BBR optimization & MTU 1280.',
    optim_auto_desc: 'Heuristic analysis & dynamic MTU adjustment.',
    optim_sync_desc:
      'Heuristic maintenance of the system kernel active. Real-time monitoring of memory leaks.',
    optim_system_optimized: 'System Optimized',
    optim_active_vector: 'Active Vector',
    optim_active: 'Optimization Active',
    optim_activate_profile: 'Activate Profile',
    // Dashboard
    quota_critical_suffix: 'in Critical Quota',
    manage: 'Manage',
    dash_active_protocol: 'Active Protocol',
    dash_active_peers: 'Active Peers',
    dash_connected: 'CONNECTED',
    dash_port_link: 'Link Port',
    subscribers: 'Subscribers',
    expire_soon_days: 'Expire ≤ 7 d',
    expired_count: 'Expired',
    most_active_client: 'Most active client',
    none: 'None',
    inactive_station: 'Inactive Station',
    telemetry_system: 'SENTINEL System',
    telemetry_live: 'Live Telemetry',
    history_unavailable: 'History unavailable — real-time data active',
    init_sentinel_flux: 'Initializing Sentinel streams...',
    check_traffic_history_conn: 'Check connection to the traffic-history service',
    data_after_audit: '(Data available after the first audit cycle)',
    rt_rates_label: 'Real-time rates (5 s) · Mbit/s',
    history_24h_label: '24 h history · MB volumes',
    tactical_distribution: 'Tactical Distribution',
    no_flux_detected: 'No flux detected',
    test_running: 'Test running...',
    rerun: 'Rerun',
    run_speedtest: 'Run Flow Test',
    // Audit
    audit_title: 'Security Audit',
    integrity_index: 'Integrity Index',
    integrity_desc: 'Calculation based on kernel, firewall and software protection status.',
    critical: 'Critical',
    audit_firewall_desc: 'Check of the UFW interface and pre-configured filtering rules.',
    audit_fw_ok: 'Device Protection OK',
    audit_fw_bad: 'Possible Network Vulnerability',
    audit_ipfwd_desc:
      'Status of the sysctl net.ipv4.ip_forward option required for vpn transit.',
    audit_ipfwd_ok: 'Data Transit Active',
    audit_ipfwd_bad: 'Tunnel Flow Interruption',
    audit_f2b_desc: 'Monitoring of SSH brute-force attempts and IP bans.',
    audit_f2b_ok: 'Brute-Force Defense OK',
    audit_f2b_bad: 'SSH Vulnerability Detected',
    audit_disk_desc: 'Root partition usage (SSD/NVMe) for the system cache.',
    // Logs
    system_event: 'System event',
    system_source: 'System',
    logs_cleared_ok: 'Logs cleared successfully',
    logs_clear_err: 'Error while clearing',
    ws_lost: 'Real-time connection lost — Automatic reconnection in progress...',
    docker_logs_prefix: 'Docker container logs',
    clear_all_logs_q: 'Clear all logs?',
    action_irreversible: 'This action is irreversible.',
    confirm_clear: 'Confirm clearing',
    filter_placeholder: 'Filter...',
    filter_logs_aria: 'Filter logs',
    tab_access_peers: 'Peers Access',
    log_tab_security: 'Security',
    tab_system_log: 'System Log',
    entries: 'entries',
    clear: 'Clear',
    col_event: 'Event',
    scanning_archives: 'Scanning archives...',
    no_record_found: 'No record found',
    // MainLayout
    twofa_banner_text: 'Your admin account has no 2FA enabled —',
    twofa_banner_cta: 'configure now',
    upd_phase_queued: 'Queued…',
    upd_phase_downloading: 'Downloading the bundle…',
    upd_phase_verifying: 'Integrity check…',
    upd_phase_building: 'Rebuilding services…',
    upd_phase_restarting: 'Restarting…',
    upd_restarting_services: 'Restarting services…',
    upd_installing: 'Installation in progress…',
    license_expired_msg: 'License expired — client creation is blocked. Renew to continue.',
    license_label: 'License:',
    days_remaining: 'day(s) remaining',
    license_renew_hint: 'remember to renew.',
    renew_via: 'To renew:',
    upd_failed_prefix: 'Update failed',
    upd_retry_next_cycle: 'Automatic retry on the next cycle.',
    upd_label: 'Update',
    upd_installed_reload: 'installed — reloading the panel…',
    upd_dont_close: 'Do not close this page — brief network outage (~30 s) during the restart.',
    upd_ready_confirm: 'ready — your confirmation is required to install it.',
    upd_scheduled: 'scheduled',
    upd_around: 'around',
    upd_can_advance: 'you can bring it forward.',
    upd_install_now: 'Install now',
    upd_available: 'Update available',
    upd_pending_approval: 'pending approval by the platform.',
    onboarding_add_vps: 'Add your VPS to access the rest of the platform',
    access_denied_admin: 'Access denied — section restricted to administrators',
    search: 'Search',
    surveillance_active: 'Monitoring Active',
    sentinel_offline: 'Sentinel Offline',
    dns_filtering_active: 'DNS Filtering Active',
    dns_interrupted: 'DNS Interrupted',
    all_rights_reserved: 'All rights reserved.',
    delete_client: 'Delete client',
    delete_permanently: 'Delete permanently',
    delete_empty_container: 'Delete the empty container',
    revoke_access_warning: 'This action will immediately revoke their system access.',
    from_container: 'from container',
    // StatusWidget / NavItems
    wg_restarted_ok: 'WireGuard service restarted.',
    wg_restart_error: 'Error during restart.',
    restarting_label: 'Restarting...',
    confirm: 'Confirm',
    change_language: 'Change language',
    restart_wireguard: 'Restart WireGuard',
    restart_wireguard_q: 'Restart WireGuard?',
    yes: 'Yes',
    no: 'No',
  },
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(localStorage.getItem('app-lang') || 'fr');

  useEffect(() => {
    localStorage.setItem('app-lang', lang);
  }, [lang]);

  const t = (key) => {
    return translations[lang]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>{children}</LanguageContext.Provider>
  );
};

export const useLang = () => useContext(LanguageContext);
