import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  fr: {
    dashboard: 'Tableau de bord',
    containers: 'Conteneurs',
    sales: 'Ventes',
    network: 'Réseau',
    users_manage: 'Utilisateurs',
    servers: 'Serveurs',
    logs: 'Logs',
    topology: 'Topologie',
    dns_editor: 'Éditeur DNS',
    optimization: 'Optimisation',
    audit: 'Audit',
    settings: 'Paramètres',
    logout: 'Déconnexion',
    configs: 'Configurations',
    support: 'Support',
    active_core: 'Cœur Actif',
    uptime: 'Temps Activité',
    reboot_system: 'Redémarrer Système',
    secure_portal: 'Espace Utilisateur Sécurisé',
    no_config: 'Aucune configuration disponible',
    contact_admin: "Contactez l'administrateur.",
    // Communs (réutilisés dans toutes les sections)
    refresh: 'Actualiser',
    status_active: 'Actif',
    status_expired: 'Expiré',
    status_suspended: 'Suspendu',
    unknown: 'Inconnu',
    edit: 'Éditer',
    delete: 'Supprimer',
    // Section Utilisateurs
    user_management: 'Gestion des Opérateurs',
    system_access_control: "Contrôle d'accès système",
    search_operator: 'Rechercher un opérateur...',
    create_access: 'Créer un Accès',
    col_identity: 'Identité Opérateur',
    col_role: 'Rôle Système',
    col_status: 'Statut',
    col_action: 'Intervention',
    edit_operator: 'Éditer Opérateur',
    delete_operator: 'Supprimer Opérateur',
    no_operator_found: 'Aucun opérateur trouvé',
    role_admin_label: 'Accès Root',
    role_manager_label: 'Accès Manager',
    role_viewer_label: 'Accès Opérateur',
    role_admin_badge: 'Admin',
    role_manager_badge: 'Manager',
    role_viewer_badge: 'Opérateur',
    // Modales Créer/Éditer utilisateur
    cancel: 'Annuler',
    optional: 'Optionnel',
    username_required: "Nom d'utilisateur requis",
    username_invalid:
      "Nom d'utilisateur invalide (2-64 caractères, lettres, chiffres, _ et - uniquement)",
    password_min: 'Mot de passe : 8 caractères minimum',
    passwords_mismatch: 'Les mots de passe ne correspondent pas',
    create_error: 'Erreur lors de la création',
    update_error: 'Erreur lors de la mise à jour',
    role_viewer_desc: 'Lecture seule',
    role_manager_desc: 'Gestion Clients',
    role_admin_desc: 'Accès complet',
    create_operator_title: 'Créer un Opérateur',
    create_operator_btn: "Créer l'Opérateur",
    edit_operator_title: "Éditer l'Opérateur",
    save: 'Enregistrer',
    field_username: 'Identifiant',
    field_password: 'Mot de Passe',
    field_confirm_password: 'Confirmer le Mot de Passe',
    placeholder_username: 'ex: operateur01',
    password_leave_empty: 'Laisser vide pour inchangé',
    confirm_new_password: 'Confirmer nouveau mot de passe',
    account_active: 'Compte Actif',
    account_suspended: 'Compte Suspendu',
    reset_2fa: 'Réinitialiser 2FA (TOTP)',
    resetting: 'Réinitialisation...',
    reset_2fa_ok: 'Secret 2FA réinitialisé',
    reset_2fa_err: 'Erreur reset 2FA',
    reset_2fa_confirm:
      'Réinitialiser le 2FA pour cet opérateur ? Il pourra se reconnecter sans son code actuel.',
    expiry: 'Expiration',
    identity_locked: 'Identité Verrouillée',
    access_level: "Niveau d'Accès",
    expiry_date: "Date d'Expiration",
    remove_expiry: "Supprimer l'expiration",
    account_status: 'Statut du Compte',
    suspended_hint: "L'utilisateur ne pourra plus se connecter jusqu'à réactivation.",
    new_password: 'Nouveau Mot de Passe',
    // Section Conteneurs
    create: 'Créer',
    unlimited: 'Illimité',
    status_online: 'En ligne',
    status_offline: 'Hors ligne',
    search_placeholder: 'Rechercher...',
    deselect_all: 'Désélectionner tout',
    select: 'Sélectionner',
    deselect: 'Désélectionner',
    selected: 'sélectionné(s)',
    peers: 'peers',
    export_csv: 'Exporter CSV',
    new_peer: 'Nouveau Peer',
    new_container: 'Nouveau Conteneur',
    col_name: 'Nom',
    col_container: 'Conteneur',
    peer_active: 'Peer actif',
    peer_offline: 'Peer hors ligne',
    expiring_soon: 'Bientôt',
    quota_usage: 'Utilisation Quota',
    disable: 'Désactiver',
    enable: 'Activer',
    disable_peer: 'Désactiver le peer',
    enable_peer: 'Activer le peer',
    qr_config: 'Configuration / QR Code',
    show_qr: 'Afficher la configuration QR Code',
    delete_peer: 'Supprimer le peer',
    modify: 'Modifier',
    never: 'Jamais',
    daily_quota: 'Quota journalier',
    data_total: 'Données Totales',
    burst_dl: 'Burst DL',
    burst_ul: 'Burst UL',
    realtime: 'Temps réel',
    masked_na: 'Masquée / N/A',
    delete_container: 'Supprimer le conteneur',
    total_volume: 'Volume Total',
    no_results: 'Aucun résultat',
    empty_container: 'Conteneur Vide',
    no_peers_in_container: 'Aucun peer dans ce conteneur',
    reconcile_error: 'Erreur de réconciliation',
    peers_reapplied: 'Peers ré-appliqués dans le tunnel',
    resync_failed: 'Échec de la resynchronisation',
    rescan: 'Ré-analyser',
    no_match: 'Aucun peer ne correspond à',
    delete_peers_first: "Supprimez d'abord les peers",
    resync_peers: 'Resynchroniser les peers',
    purge: 'Purger',
    ghosts: 'fantôme(s)',
    ghosts_purged: 'entrée(s) fantôme(s) purgée(s)',
    desync_detected: 'Désynchronisation détectée',
    orphans_desc: 'client(s) en base sans fichier sur le disque (fantômes).',
    missing_desc: 'client(s) avec fichiers OK mais absent(s) du tunnel WireGuard.',
    last_activity: 'Dernière activité',
    hours_72: '72 Heures',
    network_spectrum: 'Spectre Réseau',
    blackbox_log: 'Blackbox Log',
    scanning_logs: 'Analyse des logs...',
    no_logs: 'Aucun log',
    detected_active: 'DÉTECTÉ / ACTIF',
    inactive: 'INACTIF',
    real_ip: 'IP Réelle (Endpoint)',
    real_handshake: 'Handshake Réel',
  },
  en: {
    dashboard: 'Dashboard',
    containers: 'Containers',
    sales: 'Sales',
    network: 'Network',
    users_manage: 'Users',
    servers: 'Servers',
    logs: 'Logs',
    topology: 'Topology',
    dns_editor: 'DNS Editor',
    optimization: 'Optimization',
    audit: 'Audit',
    settings: 'Settings',
    logout: 'Logout',
    configs: 'Configurations',
    support: 'Support',
    active_core: 'Active Core',
    uptime: 'Uptime',
    reboot_system: 'Reboot System',
    secure_portal: 'Secure User Portal',
    no_config: 'No configuration available',
    contact_admin: 'Contact administrator.',
    // Common (reused across sections)
    refresh: 'Refresh',
    status_active: 'Active',
    status_expired: 'Expired',
    status_suspended: 'Suspended',
    unknown: 'Unknown',
    edit: 'Edit',
    delete: 'Delete',
    // Users section
    user_management: 'Operator Management',
    system_access_control: 'System Access Control',
    search_operator: 'Search an operator...',
    create_access: 'Create Access',
    col_identity: 'Operator Identity',
    col_role: 'System Role',
    col_status: 'Status',
    col_action: 'Action',
    edit_operator: 'Edit Operator',
    delete_operator: 'Delete Operator',
    no_operator_found: 'No operator found',
    role_admin_label: 'Root Access',
    role_manager_label: 'Manager Access',
    role_viewer_label: 'Operator Access',
    role_admin_badge: 'Admin',
    role_manager_badge: 'Manager',
    role_viewer_badge: 'Operator',
    // Create/Edit user modals
    cancel: 'Cancel',
    optional: 'Optional',
    username_required: 'Username required',
    username_invalid: 'Invalid username (2-64 chars, letters, digits, _ and - only)',
    password_min: 'Password: 8 characters minimum',
    passwords_mismatch: 'Passwords do not match',
    create_error: 'Creation error',
    update_error: 'Update error',
    role_viewer_desc: 'Read-only',
    role_manager_desc: 'Client management',
    role_admin_desc: 'Full access',
    create_operator_title: 'Create Operator',
    create_operator_btn: 'Create Operator',
    edit_operator_title: 'Edit Operator',
    save: 'Save',
    field_username: 'Username',
    field_password: 'Password',
    field_confirm_password: 'Confirm Password',
    placeholder_username: 'e.g. operator01',
    password_leave_empty: 'Leave empty to keep unchanged',
    confirm_new_password: 'Confirm new password',
    account_active: 'Active Account',
    account_suspended: 'Suspended Account',
    reset_2fa: 'Reset 2FA (TOTP)',
    resetting: 'Resetting...',
    reset_2fa_ok: '2FA secret reset',
    reset_2fa_err: '2FA reset error',
    reset_2fa_confirm:
      'Reset 2FA for this operator? They will be able to log in again without their current code.',
    expiry: 'Expiry',
    identity_locked: 'Locked Identity',
    access_level: 'Access Level',
    expiry_date: 'Expiry Date',
    remove_expiry: 'Remove expiry',
    account_status: 'Account Status',
    suspended_hint: 'The user will not be able to log in until reactivated.',
    new_password: 'New Password',
    // Containers section
    create: 'Create',
    unlimited: 'Unlimited',
    status_online: 'Online',
    status_offline: 'Offline',
    search_placeholder: 'Search...',
    deselect_all: 'Deselect all',
    select: 'Select',
    deselect: 'Deselect',
    selected: 'selected',
    peers: 'peers',
    export_csv: 'Export CSV',
    new_peer: 'New Peer',
    new_container: 'New Container',
    col_name: 'Name',
    col_container: 'Container',
    peer_active: 'Peer online',
    peer_offline: 'Peer offline',
    expiring_soon: 'Soon',
    quota_usage: 'Quota Usage',
    disable: 'Disable',
    enable: 'Enable',
    disable_peer: 'Disable peer',
    enable_peer: 'Enable peer',
    qr_config: 'Configuration / QR Code',
    show_qr: 'Show QR Code configuration',
    delete_peer: 'Delete peer',
    modify: 'Edit',
    never: 'Never',
    daily_quota: 'Daily quota',
    data_total: 'Total Data',
    burst_dl: 'Burst DL',
    burst_ul: 'Burst UL',
    realtime: 'Real-time',
    masked_na: 'Masked / N/A',
    delete_container: 'Delete container',
    total_volume: 'Total Volume',
    no_results: 'No results',
    empty_container: 'Empty Container',
    no_peers_in_container: 'No peer in this container',
    reconcile_error: 'Reconciliation error',
    peers_reapplied: 'Peers re-applied in the tunnel',
    resync_failed: 'Resync failed',
    rescan: 'Rescan',
    no_match: 'No peer matches',
    delete_peers_first: 'Delete the peers first',
    resync_peers: 'Resync the peers',
    purge: 'Purge',
    ghosts: 'ghost(s)',
    ghosts_purged: 'ghost entry(ies) purged',
    desync_detected: 'Desync detected',
    orphans_desc: 'client(s) in DB with no file on disk (ghosts).',
    missing_desc: 'client(s) with OK files but missing from the WireGuard tunnel.',
    last_activity: 'Last activity',
    hours_72: '72 Hours',
    network_spectrum: 'Network Spectrum',
    blackbox_log: 'Blackbox Log',
    scanning_logs: 'Scanning logs...',
    no_logs: 'No logs found',
    detected_active: 'DETECTED / ACTIVE',
    inactive: 'INACTIVE',
    real_ip: 'Real IP (Endpoint)',
    real_handshake: 'Real Handshake',
  },
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(localStorage.getItem('app-lang') || 'fr');

  useEffect(() => {
    localStorage.setItem('app-lang', lang);
  }, [lang]);

  const t = (key) => {
    return translations[lang]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>{children}</LanguageContext.Provider>
  );
};

export const useLang = () => useContext(LanguageContext);
